/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef _HDMI_TA_H_
#define _HDMI_TA_H_

#define TZ_TA_HDMI_NAME "HDMI TA"
#define TZ_TA_HDMI_UUID "eaf800b0-da1b-11e2-a28f-0800200c9a66"
#define PTA_HDMITX_UUID   {0xeaf800b0, 0xda1b, 0x11e2, \
	{0xa2, 0x8f, 0x08, 0x00, 0x20, 0x0c, 0x9a, 0x66} }

enum HDMI_TA_SERVICE_CMD_T {
	HDMI_TA_WRITE_REG = 0,
	HDMI_TA_DPI1_WRITE_REG,
	HDMI_TA_INSTALL_HDCP_KEY,
	HDMI_TA_LOAD_HDCP_KEY,
	HDMI_TA_GET_HDCP_AKSV,
	HDMI_TA_HDCP_ENC_EN,
	HDMI_TA_HDCP_RST,
	HDMI_TA_VID_UNMUTE,
	HDMI_TA_AUD_UNMUTE,
	HDMI_TA_PROTECT_HDMIREG,
	HDMI_TA_LOAD_ROM,
	HDMI_TA_HDCP_FAIL,
	HDMI_TA_TEST_HDCP_VERSION,
	HDMI_TA_SET_LOG_LEVEL,
	HDMI_TA_HDCP_OFF,
	HDMI_TA_READ_STATUS,
	HDMI_TA_LOAD_RAM,
	HDMI_TA_SECURE_REG_ENTRY,
	HDMI_TA_GET_EFUSE,
	HDMI_TA_GET_HDR10p_VSIF_Info,
	HDMI_TA_GET_HDCP_TYPE,
	HDMI_TA_GET_HDCP2_INFO,
	HDMI_TA_HDCP_ENC_STATUS,
	HDMI_TA_LOAD_EMP,
	HDMI_TA_SET_CONTENT_STREAM_MANAGE,
	HDMI_TA_GET_CONTENT_STREAM_MANAGE,
	HDMI_TA_GET_LOWEST_HDCP_TYPE,
};

enum TA_RETURN_HDMI_HDCP_STATE {
	TA_RETURN_HDCP_STATE_ENC_EN = 0,
	TA_RETURN_HDCP_STATE_ENC_FAIL,
	TA_RETURN_HDCP_STATE_ENC_UNKNOWN,
};

enum TA_RETURN_HDCP_TYPE {
	TA_RETURN_HDCP_TYPE_HDMI_DISCONNECT = -1,
	TA_RETURN_HDCP_TYPE_SINK_NOT_SUPPORT = 0,
	TA_RETURN_HDCP_TYPE_HDCP_14 = 1,
	TA_RETURN_HDCP_TYPE_HDCP_23 = 4,
	TA_RETURN_HDCP_TYPE_UNAUTHORIZED = 5,
};

enum TA_HDCP_CONTENT_STREAM_MANAGEMENT_TYPE {
	//content stream may be transmitted by repeater to all hdcp devices.
	TA_HDCP_CONTENT_STREAM_MANAGEMENT_TYPE_0 = 0x0,
	//content stream must not be transmitted by repeater to hdcp 1.x devices and 2.0 repeaters.
	TA_HDCP_CONTENT_STREAM_MANAGEMENT_TYPE_1 = 0x1,
	TA_HDCP_CONTENT_STREAM_MANAGEMENT_TYPE_RESERVE = 0xff,
};

extern unsigned char vTaGetHdcpStatus(void);
extern unsigned char vTaGetHdmiStatus(void);

#endif
