
ccflags-y += -I$(srctree)/include/                              \
             -I$(srctree)/include/linux/                        \
             -I$(srctree)/include/soc/mediatek/                 \
             -I$(srctree)/drivers/staging/android/ion/mtk       \
             -I$(srctree)/drivers/staging/android/ion/          \
             -I$(srctree)/include/trustzone/

obj-y += irt_hal.o irt_debug.o irt_if.o