ccflags-y +=  -I$(srctree)/drivers/staging/android/uapi/ \
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/inc	\
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/	\
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/videox/	\
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/adl/	 \
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/hdr/dovi_hdr/	\
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/disp_hal/ml/ \
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/disp_hal/adl/	\
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/disp_hal/hdr/dovi/	\
			-I$(srctree)/include/trustzone \
			-I$(srctree)/drivers/misc/mediatek/mmp \
			-I$(srctree)/drivers/misc/mediatek/sync/      \
			-I$(srctree)/drivers/staging/android/mtk_ion \
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/disp_hal/vdout_sys	\
			-I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys/disp_hal/disp_sys	\
			-I$(srctree)/drivers/misc/mediatek/hdmi/hdmitx/$(CONFIG_MTK_VIDEO_PLATFORM)/inc	\
			-I$(srctree)/include/linux/soc/mediatek \
#common
obj-y += disp_ml_if.o
obj-y += disp_ml_cmd.o
# EOF
