/*
 * mt8696-reg.h  --  Mediatek 8696 audio driver reg definition
 *
 * Copyright (c) 2020 MediaTek Inc.
 * Author: Sail Yang <sail.yang@mediatek.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _MT8696_REG_H_
#define _MT8696_REG_H_

/*****************************************************************************
 *                  R E G I S T E R       D E F I N I T I O N
 *****************************************************************************/
#define AUDIO_TOP_CON0					0x0000
#define AUDIO_TOP_CON1					0x0004
#define AUDIO_TOP_CON2					0x0008
#define AUDIO_TOP_CON3					0x000c
#define AUDIO_TOP_CON4					0x0010
#define AUDIO_TOP_CON5					0x0014

#define ASYS_IRQ_CONFIG					0x0110
#define ASYS_IRQ1_CON					0x0114
#define ASYS_IRQ2_CON					0x0118
#define ASYS_IRQ3_CON					0x011c

#define ASYS_IRQ_CLR					0x0154
#define ASYS_IRQ_STATUS					0x0158

#define ASYS_IRQ_MON1					0x015c
#define ASYS_IRQ_MON2					0x0160

#define AFE_IRQ_STATUS					0x0174
#define AFE_IRQ_MASK					0x0178
#define ASYS_IRQ_MASK					0x017c

#define AFE_SINEGEN_CON0				0x01f0
#define AFE_SINEGEN_CON1				0x01f4
#define AFE_SINEGEN_CON2				0x01f8
#define AFE_SINEGEN_CON3				0x01fc

#define AFE_HDMI_CONN0					0x0390
#define AFE_HDMI_CONN1					0x0398

#define AFE_APLL_TUNER_CFG				0x03f8
#define AFE_APLL_TUNER_CFG1				0x03fc

#define ASYS_TOP_CON					0x0600

#define AFE_CONN_24BIT					0x06b8
#define AFE_CONN_16BIT					0x06bc

#define AFE_DAC_CON0					0x1200
#define AFE_DAC_CON1					0x1204
#define AFE_DAC_MON0					0x1218

#define AFE_DL5_BASE					0x1280
#define AFE_DL5_CUR					0x1284
#define AFE_DL5_END					0x1288
#define AFE_DL5_CON0					0x128c
#define AFE_DL8_BASE					0x12b0
#define AFE_DL8_CUR					0x12b4
#define AFE_DL8_END					0x12b8
#define AFE_DL8_CON0					0x12bc
#define AFE_UL1_BASE					0x1300
#define AFE_UL1_CUR					0x1304
#define AFE_UL1_END					0x1308
#define AFE_UL1_CON0					0x130c

#define AFE_DL8_CHK_SUM1				0x1400
#define AFE_DL8_CHK_SUM2				0x1404
#define AFE_DL8_CHK_SUM3				0x1408
#define AFE_DL8_CHK_SUM4				0x140c
#define AFE_DL8_CHK_SUM5				0x1410
#define AFE_DL8_CHK_SUM6				0x1414

#define AFE_UL1_CHK_SUM1				0x1450
#define AFE_UL1_CHK_SUM2				0x1454

#define AFE_DL5_CHK_SUM1				0x14d0
#define AFE_DL5_CHK_SUM2				0x14d4

#define AFE_BUS_MON1					0x1540

#define UL1_MOD2AGT_CNT_LAT				0x1568

#define AFE_MEMIF_AGENT_FS_CON0				0x15a0
#define AFE_MEMIF_AGENT_FS_CON1				0x15a4
#define AFE_MEMIF_AGENT_FS_CON2				0x15a8

#define AFE_MEMIF_BURST_CFG				0x1600
#define AFE_MEMIF_BUF_FULL_MON				0x1610
#define AFE_MEMIF_BUF_MON2				0x1620
#define AFE_MEMIF_BUF_MON4				0x1628
#define AFE_MEMIF_BUF_MON6				0x1630

#define AFE_NORMAL_BASE_ADR_MSB				0x192c
#define AFE_NORMAL_END_ADR_MSB				0x1930

#define AFE_LOOPBACK_CFG0				0x1950

#define ETDM_IN2_MONITOR				0x22c4
#define ETDM_OUT1_MONITOR				0x22d0
#define ETDM_OUT2_MONITOR				0x22d4

#define ETDM_COWORK_CON0				0x22f0
#define ETDM_COWORK_CON1				0x22f4
#define ETDM_COWORK_CON2				0x22f8
#define ETDM_COWORK_CON3				0x22fc

#define ETDM_IN2_CON0					0x2320
#define ETDM_IN2_CON1					0x2324
#define ETDM_IN2_CON2					0x2328
#define ETDM_IN2_CON3					0x232c
#define ETDM_IN2_CON4					0x2330
#define ETDM_IN2_CON5					0x2334
#define ETDM_IN2_CON6					0x2338
#define ETDM_IN2_CON7					0x233c

#define ETDM_OUT1_CON0					0x2380
#define ETDM_OUT1_CON1					0x2384
#define ETDM_OUT1_CON2					0x2388
#define ETDM_OUT1_CON3					0x238c
#define ETDM_OUT1_CON4					0x2390
#define ETDM_OUT1_CON5					0x2394
#define ETDM_OUT1_CON6					0x2398
#define ETDM_OUT1_CON7					0x239c

#define ETDM_OUT2_CON0					0x23a4
#define ETDM_OUT2_CON1					0x23a8
#define ETDM_OUT2_CON2					0x23ac
#define ETDM_OUT2_CON3					0x23b0
#define ETDM_OUT2_CON4					0x23b4
#define ETDM_OUT2_CON5					0x23b8
#define ETDM_OUT2_CON6					0x23bc
#define ETDM_OUT2_CON7					0x23c0

#define ETDM_OUT1_DSD_FADE_CON				0x2400
#define ETDM_OUT1_DSD_FADE_CON1				0x2404

#define MAX_REGISTER					ETDM_OUT1_DSD_FADE_CON1

#define AFE_IRQ_STATUS_BITS				0x1feffff
#define AFE_IRQ_MCU_CLR_BITS				0x1fe
#define ASYS_IRQ_CLR_BITS				0xffff

/* AUDIO_TOP_CON0 (0x0000) */
#define AUD_TCON0_AHB_IDLE_EN				BIT(30)
#define AUD_TCON0_AHB_IDLE_EN_EXT			BIT(29)
#define AUD_TCON0_PDN_TML				BIT(27)
#define AUD_TCON0_PDN_AFE				BIT(2)

/* AUDIO_TOP_CON4 (0x0010) */
#define AUD_TCON4_PCM2_TXRX_SEL				BIT(31)
#define AUD_TCON4_PDN_A2SYS				BIT(22)
#define AUD_TCON4_PDN_A1SYS				BIT(21)
#define AUD_TCON4_PDN_ETDM_OUT2				BIT(7)
#define AUD_TCON4_PDN_ETDM_OUT1				BIT(6)
#define AUD_TCON4_PDN_ETDM_IN				BIT(0)

/* AUDIO_TOP_CON5 (0x0014) */
#define AUD_TCON5_PDN_DL8				BIT(13)
#define AUD_TCON5_PDN_DL5				BIT(10)
#define AUD_TCON5_PDN_UL1				BIT(0)

/* ASMO_TIMING_CON0 (0x0100) */
#define ASMO_TIMING_CON0_ASMO0_MODE_MASK		GENMASK(4, 0)
#define ASMO_TIMING_CON0_ASMO0_MODE_VAL(x)		((x & 0x1f) << 0)

/* PWR1_ASM_CON1 (0x0108) */
#define PWR1_ASM_CON1_GASRC0_CALI_CK_SEL_MASK		BIT(2)
#define PWR1_ASM_CON1_GASRC0_CALI_CK_SEL(x)		(x << 2)
#define PWR1_ASM_CON1_GASRC1_CALI_CK_SEL_MASK		BIT(5)
#define PWR1_ASM_CON1_GASRC1_CALI_CK_SEL(x)		(x << 5)
#define PWR1_ASM_CON1_GASRC2_CALI_CK_SEL_MASK		BIT(20)
#define PWR1_ASM_CON1_GASRC2_CALI_CK_SEL(x)		(x << 20)
#define PWR1_ASM_CON1_GASRC3_CALI_CK_SEL_MASK		BIT(23)
#define PWR1_ASM_CON1_GASRC3_CALI_CK_SEL(x)		(x << 23)
#define PWR1_ASM_CON1_DL_ASRC_CALI_CK_SEL_MASK		BIT(26)
#define PWR1_ASM_CON1_DL_ASRC_CALI_CK_SEL(x)		(x << 26)

/* AFE_IRQ_MASK (0x0178) */
#define AFE_IRQ_MASK_EN_BITS				(0x70fff)
#define AFE_IRQ_MASK_EN_MASK				GENMASK(24, 0)

/* AFE_SINEGEN_CON0 (0x01f0) */
#define AFE_SINEGEN_CON0_INIT_MASK			(0x1f01f)
#define AFE_SINEGEN_CON0_INIT_VAL			(0x1001)
#define AFE_SINEGEN_CON0_EN				BIT(26)
#define AFE_SINEGEN_CON0_MODE_MASK			GENMASK(31, 27)
#define AFE_SINEGEN_CON0_FREQ_DIV_CH2_MASK		GENMASK(16, 12)
#define AFE_SINEGEN_CON0_FREQ_DIV_CH1_MASK		GENMASK(4, 0)
#define AFE_SINEGEN_CON0_FREQ_DIV_CH2(x)		(((x) & 0x1f) << 12)
#define AFE_SINEGEN_CON0_FREQ_DIV_CH1(x)		(((x) & 0x1f) << 0)

/* AFE_SINEGEN_CON1 (0x01f4) */
#define AFE_SINEGEN_CON1_TIMING_CH2_MASK		GENMASK(25, 21)
#define AFE_SINEGEN_CON1_TIMING_CH1_MASK		GENMASK(20, 16)
#define AFE_SINEGEN_CON1_TIMING_CH2(x)			(((x) & 0x1f) << 21)
#define AFE_SINEGEN_CON1_TIMING_CH1(x)			(((x) & 0x1f) << 16)
#define AFE_SINEGEN_CON1_TIMING_8K			(0)
#define AFE_SINEGEN_CON1_TIMING_12K			(1)
#define AFE_SINEGEN_CON1_TIMING_16K			(2)
#define AFE_SINEGEN_CON1_TIMING_24K			(3)
#define AFE_SINEGEN_CON1_TIMING_32K			(4)
#define AFE_SINEGEN_CON1_TIMING_48K			(5)
#define AFE_SINEGEN_CON1_TIMING_96K			(6)
#define AFE_SINEGEN_CON1_TIMING_192K			(7)
#define AFE_SINEGEN_CON1_TIMING_384K			(8)
#define AFE_SINEGEN_CON1_TIMING_7P35K			(16)
#define AFE_SINEGEN_CON1_TIMING_11P025K			(17)
#define AFE_SINEGEN_CON1_TIMING_14P7K			(18)
#define AFE_SINEGEN_CON1_TIMING_22P05K			(19)
#define AFE_SINEGEN_CON1_TIMING_29P4K			(20)
#define AFE_SINEGEN_CON1_TIMING_44P1K			(21)
#define AFE_SINEGEN_CON1_TIMING_88P2K			(22)
#define AFE_SINEGEN_CON1_TIMING_176P4K			(23)
#define AFE_SINEGEN_CON1_TIMING_352P8K			(24)
#define AFE_SINEGEN_CON1_TIMING_DL_1X_EN		(30)
#define AFE_SINEGEN_CON1_TIMING_SGEN_EN			(31)
#define AFE_SINEGEN_CON1_GASRC_IN_SGEN			BIT(13)
#define AFE_SINEGEN_CON1_GASRC_OUT_SGEN			BIT(12)

/* AFE_SPDIF_OUT_CON0 (0x0380) */
#define AFE_SPDIF_OUT_CON0_TIMING_MASK			BIT(1)
#define AFE_SPDIF_OUT_CON0_TIMING_ON			(1 << 1)
#define AFE_SPDIF_OUT_CON0_TIMING_OFF			(0 << 1)

/* AFE_APLL_TUNER_CFG (0x03f8) */
#define AFE_APLL_TUNER_CFG_MASK				GENMASK(15, 1)
#define AFE_APLL_TUNER_CFG_EN_MASK			GENMASK(0, 0)

/* AFE_APLL_TUNER_CFG1 (0x03fc) */
#define AFE_APLL_TUNER_CFG1_MASK			GENMASK(15, 1)
#define AFE_APLL_TUNER_CFG1_EN_MASK			GENMASK(0, 0)

/* AFE_IEC_CFG (0x0480) */
#define AFE_IEC_CFG_SET_MASK				(0xff9e0073)
#define AFE_IEC_CFG_SW_RST_MASK				BIT(23)
#define AFE_IEC_CFG_FORCE_UPDATE_SIZE(x)		(((x) & 0xff) << 24)
#define AFE_IEC_CFG_FORCE_UPDATE			BIT(20)
#define AFE_IEC_CFG_SWAP_IEC_BYTE			BIT(17)
#define AFE_IEC_CFG_EN_MASK				BIT(16)
#define AFE_IEC_CFG_RAW_24BIT_SWITCH			BIT(6)
#define AFE_IEC_CFG_RAW_24BIT				BIT(5)
#define AFE_IEC_CFG_VALID_DATA				BIT(4)
#define AFE_IEC_CFG_NO_SW_RST				(1 << 23)
#define AFE_IEC_CFG_SW_RST				(0 << 23)
#define AFE_IEC_CFG_ENABLE_CTRL				(1 << 16)
#define AFE_IEC_CFG_DISABLE_CTRL			(0 << 16)
#define AFE_IEC_CFG_MUTE_DATA				(1 << 3)
#define AFE_IEC_CFG_UNMUTE_DATA				(0 << 3)
#define AFE_IEC_CFG_ENCODED_DATA			(1 << 1)
#define AFE_IEC_CFG_PCM_DATA				(0 << 1)
#define AFE_IEC_CFG_DATA_SRC_DRAM			(1 << 0)

/* AFE_IEC_NSNUM (0x0484) */
#define AFE_IEC_NSNUM_SET_MASK				(0x3fff3fff)
#define AFE_IEC_NSNUM_INTR_NUM(x)			(((x) & 0x3fff) << 16)
#define AFE_IEC_NSNUM_SAM_NUM(x)			(((x) & 0x3fff) << 0)

/* AFE_IEC_BURST_INFO (0x0488) */
#define AFE_IEC_BURST_INFO_READY_MASK			BIT(16)
#define AFE_IEC_BURST_INFO_NOT_READY			(1 << 16)
#define AFE_IEC_BURST_INFO_READY			(0 << 16)
#define AFE_IEC_BURST_INFO_SET_MASK			GENMASK(15, 0)

/* AFE_IEC_BURST_LEN (0x048c) */
#define AFE_IEC_BURST_LEN_SET_MASK			GENMASK(18, 0)

/* AFE_IEC_CHL_STAT0 (0x04a0)
 * AFE_IEC_CHL_STAT1 (0x04a4)
 * AFE_IEC_CHR_STAT0 (0x04a8)
 * AFE_IEC_CHR_STAT1 (0x04ac)
 */
#define AFE_IEC_CH_STAT0_SET_MASK			GENMASK(31, 0)
#define AFE_IEC_CH_STAT1_SET_MASK			GENMASK(15, 0)

/* AFE_SPDIFIN_CFG0 (0x0500) */
#define AFE_SPDIFIN_CFG0_SET_MASK			(0x3ffff7a)
#define AFE_SPDIFIN_CFG0_MAX_LEN_NUM(x)			(((x) & 0xff) << 16)
#define AFE_SPDIFIN_CFG0_GMAT_BC_256_CYCLES		(3 << 24)
#define AFE_SPDIFIN_CFG0_DE_SEL_3_SAMPLES		(0 << 13)
#define AFE_SPDIFIN_CFG0_DE_SEL_14_SAMPLES		(1 << 13)
#define AFE_SPDIFIN_CFG0_DE_SEL_30_SAMPLES		(2 << 13)
#define AFE_SPDIFIN_CFG0_DE_SEL_CNT			(3 << 13)
#define AFE_SPDIFIN_CFG0_DE_CNT(x)			(((x) & 0x1f) << 8)
#define AFE_SPDIFIN_CFG0_INT_EN				BIT(6)
#define AFE_SPDIFIN_CFG0_DERR2IDLE_EN			(BIT(5)|BIT(4))
#define AFE_SPDIFIN_CFG0_DPERR2IDLE_EN			BIT(3)
#define AFE_SPDIFIN_CFG0_FLIP				BIT(1)
#define AFE_SPDIFIN_CFG0_EN				BIT(0)

/* AFE_SPDIFIN_CFG1 (0x0504) */
#define AFE_SPDIFIN_CFG1_SET_MASK			(0xfff10073)
#define AFE_SPDIFIN_CFG1_FIFOSTART_MASK			GENMASK(6, 4)
#define AFE_SPDIFIN_CFG1_CHSTS_INT			BIT(30)
#define AFE_SPDIFIN_CFG1_CHSTS_CHANGE_INT		BIT(29)
#define AFE_SPDIFIN_CFG1_TIMEOUT_INT			BIT(28)
#define AFE_SPDIFIN_CFG1_PREAMBLE_ERR			BIT(20)
#define AFE_SPDIFIN_CFG1_SEL_DEC0_CLK_EN		BIT(1)
#define AFE_SPDIFIN_CFG1_SEL_DEC0_DATA_EN		BIT(0)
#define AFE_SPDIFIN_CFG1_SEL_BCK_SPDIFIN		(0x1 << 16)
#define AFE_SPDIFIN_CFG1_FIFOSTART_5POINTS		(0x1 << 4)
#define AFE_SPDIFIN_CFG1_INT_BITS			(0x7f1 << 20)

/* AFE_SPDIFIN_DEBUG1 (0x0520) */
#define AFE_SPDIFIN_DEBUG1_DATALAT_ERR			BIT(10)
#define AFE_SPDIFIN_DEBUG1_CS_MASK			GENMASK(28, 24)

/* AFE_SPDIFIN_DEBUG2 (0x0524) */
#define AFE_SPDIFIN_DEBUG2_FIFO_ERR			(BIT(31)|BIT(30))
#define AFE_SPDIFIN_DEBUG2_CHSTS_INT_FLAG		BIT(26)
#define AFE_SPDIFIN_DEBUG2_PERR_9TIMES_FLAG		BIT(25)

/* AFE_SPDIFIN_DEBUG3 (0x0528) */
#define AFE_SPDIFIN_DEBUG3_ALL_ERR			GENMASK(6, 0)
#define AFE_SPDIFIN_DEBUG3_PRE_ERR_NON_STS		BIT(0)
#define AFE_SPDIFIN_DEBUG3_PRE_ERR_B_STS		BIT(1)
#define AFE_SPDIFIN_DEBUG3_PRE_ERR_M_STS		BIT(2)
#define AFE_SPDIFIN_DEBUG3_PRE_ERR_W_STS		BIT(3)
#define AFE_SPDIFIN_DEBUG3_PRE_ERR_BITCNT_STS		BIT(4)
#define AFE_SPDIFIN_DEBUG3_PRE_ERR_PARITY_STS		BIT(5)
#define AFE_SPDIFIN_DEBUG3_TIMEOUT_ERR_STS		BIT(6)
#define AFE_SPDIFIN_DEBUG3_CHSTS_PREAMPHASIS_STS	BIT(7)

/* AFE_SPDIFIN_EC (0x0530) */
#define AFE_SPDIFIN_EC_CLEAR_ALL			(0x30fff)
#define AFE_SPDIFIN_EC_PRE_ERR_CLEAR			BIT(0)
#define AFE_SPDIFIN_EC_PRE_ERR_B_CLEAR			BIT(1)
#define AFE_SPDIFIN_EC_PRE_ERR_M_CLEAR			BIT(2)
#define AFE_SPDIFIN_EC_PRE_ERR_W_CLEAR			BIT(3)
#define AFE_SPDIFIN_EC_PRE_ERR_BITCNT_CLEAR		BIT(4)
#define AFE_SPDIFIN_EC_PRE_ERR_PARITY_CLEAR		BIT(5)
#define AFE_SPDIFIN_EC_FIFO_ERR_CLEAR			(BIT(7)|BIT(6))
#define AFE_SPDIFIN_EC_TIMEOUT_INT_CLEAR		BIT(8)
#define AFE_SPDIFIN_EC_CHSTS_PREAMPHASIS_CLEAR		BIT(9)
#define AFE_SPDIFIN_EC_USECODE_COLLECTION_CLEAR		BIT(10)
#define AFE_SPDIFIN_EC_CHSTS_COLLECTION_CLEAR		BIT(11)
#define AFE_SPDIFIN_EC_DATA_LRCK_CHANGE_CLEAR		BIT(16)
#define AFE_SPDIFIN_EC_DATA_LATCH_CLEAR			BIT(17)

/* AFE_SPDIFIN_INT_EXT (0x0548) */
#define AFE_SPDIFIN_INT_EXT_INPUT_SEL_MASK	GENMASK(15, 14)
#define AFE_SPDIFIN_INT_EXT_SET_MASK		(0xeff00)
#define AFE_SPDIFIN_INT_EXT_DATALAT_ERR_EN	BIT(17)
#define AFE_SPDIFIN_INT_EXT_SEL_OPTICAL		(0 << 14)
#define AFE_SPDIFIN_INT_EXT_SEL_COAXIAL		(1 << 14)
#define AFE_SPDIFIN_INT_EXT_SEL_ARC		(2 << 14)
#define AFE_SPDIFIN_INT_EXT_SEL_TIED_LOW	(3 << 14)

/* AFE_SPDIFIN_INT_EXT2 (0x054c) */
#define AFE_SPDIFIN_INT_EXT2_ROUGH_FS_MASK	GENMASK(31, 28)
#define AFE_SPDIFIN_INT_EXT2_FS_NOT_DEFINED	(0 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_32K		(1 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_44D1K		(2 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_48K		(3 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_64K		(4 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_88D2K		(5 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_96K		(6 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_128K		(7 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_144K		(8 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_176D4K		(9 << 28)
#define AFE_SPDIFIN_INT_EXT2_FS_192K		(10 << 28)
#define AFE_SPDIFIN_INT_EXT2_LRCK_CHANGE	BIT(27)
#define SPDIFIN_594MODE_MASK			(1 << 17)
#define SPDIFIN_594MODE_EN			(1 << 17)

/* ASYS_TOP_CON (0x0600) */
#define ASYS_TCON_A1SYS_TIMING_ON		BIT(0)
#define ASYS_TCON_A2SYS_TIMING_ON		BIT(1)

/* ETDM_COWORK_CON0 (0x22f0) */
#define ETDM_COWORK_CON0_OUT1_DAT_SEL_MASK			GENMASK(15, 12)
#define ETDM_COWORK_CON0_OUT1_DAT_SEL_IN2			(0x5 << 12)
#define ETDM_COWORK_CON0_OUT1_DAT_SEL_OUT1			(0xa << 12)
#define ETDM_COWORK_CON0_OUT1_DAT_SEL_OUT2			(0xc << 12)
#define ETDM_COWORK_CON0_OUT1_SYNC_SEL_MASK			GENMASK(19, 16)
#define ETDM_COWORK_CON0_OUT1_SYNC_SEL_IN2			(0x4 << 16)
#define ETDM_COWORK_CON0_OUT1_SYNC_SEL_OUT2			(0xc << 16)
#define ETDM_COWORK_CON0_OUT1_SLV_SEL_MASK			GENMASK(23, 20)
#define ETDM_COWORK_CON0_OUT1_SLV_SEL_IN2_MAS			(0x4 << 20)
#define ETDM_COWORK_CON0_OUT1_SLV_SEL_IN2_SLV			(0x5 << 20)
#define ETDM_COWORK_CON0_OUT1_SLV_SEL_OUT1_SLV			(0xb << 20)
#define ETDM_COWORK_CON0_OUT1_SLV_SEL_OUT2_MAS			(0xc << 20)
#define ETDM_COWORK_CON0_OUT1_SLV_SEL_OUT2_SLV			(0xd << 20)

/* ETDM_COWORK_CON1 (0x22f4) */
#define ETDM_COWORK_CON1_LRCK2CNT_SEL_MASK			GENMASK(28, 25)
#define ETDM_COWORK_CON1_LRCK2CNT_SEL_IN_MAS			(0x4 << 25)
#define ETDM_COWORK_CON1_LRCK2CNT_SEL_OUT_MAS			(0xa << 25)

/* ETDM_COWORK_CON2 (0x22f8) */
#define ETDM_COWORK_CON2_OUT2_DAT_SEL_MASK			GENMASK(3, 0)
#define ETDM_COWORK_CON2_OUT2_DAT_SEL_IN2			(0x5)
#define ETDM_COWORK_CON2_OUT2_DAT_SEL_OUT1			(0xa)
#define ETDM_COWORK_CON2_OUT2_DAT_SEL_OUT2			(0xc)
#define ETDM_COWORK_CON2_OUT2_SYNC_SEL_MASK			GENMASK(7, 4)
#define ETDM_COWORK_CON2_OUT2_SYNC_SEL_IN2			(0x4 << 4)
#define ETDM_COWORK_CON2_OUT2_SYNC_SEL_OUT1			(0xa << 4)
#define ETDM_COWORK_CON2_OUT2_SLV_SEL_MASK			GENMASK(11, 8)
#define ETDM_COWORK_CON2_OUT2_SLV_SEL_IN2_SLV			(0x4 << 8)
#define ETDM_COWORK_CON2_OUT2_SLV_SEL_IN2_MAS			(0x5 << 8)
#define ETDM_COWORK_CON2_OUT2_SLV_SEL_OUT1_MAS			(0xa << 8)
#define ETDM_COWORK_CON2_OUT2_SLV_SEL_OUT1_SLV			(0xb << 8)
#define ETDM_COWORK_CON2_OUT2_SLV_SEL_OUT2_SLV			(0xd << 8)
#define ETDM_COWORK_CON2_IN2_SLV_SEL_MASK			GENMASK(27, 24)
#define ETDM_COWORK_CON2_IN2_SLV_SEL_IN2_SLV			(0x5 << 24)
#define ETDM_COWORK_CON2_IN2_SLV_SEL_OUT1_MAS			(0xa << 24)
#define ETDM_COWORK_CON2_IN2_SLV_SEL_OUT1_SLV			(0xb << 24)
#define ETDM_COWORK_CON2_IN2_SLV_SEL_OUT2_MAS			(0xc << 24)
#define ETDM_COWORK_CON2_IN2_SLV_SEL_OUT2_SLV			(0xd << 24)
#define ETDM_COWORK_CON2_IN2_SYNC_SEL_MASK			GENMASK(31, 28)
#define ETDM_COWORK_CON2_IN2_SYNC_SEL_OUT1			(0xa << 28)
#define ETDM_COWORK_CON2_IN2_SYNC_SEL_OUT2			(0xc << 28)

/* ETDM_COWORK_CON3 (0x22fc) */
#define ETDM_COWORK_CON3_IN2_DAT_SEL_MASK			GENMASK(3, 0)
#define ETDM_COWORK_CON3_IN2_DAT_SEL_IN2			(0x4 << 0)
#define ETDM_COWORK_CON3_IN2_DAT_SEL_OUT1_D0			(0xa << 0)
#define ETDM_COWORK_CON3_IN2_DAT_SEL_OUT1_D1			(0xb << 0)
#define ETDM_COWORK_CON3_IN2_DAT_SEL_OUT2_D0			(0xc << 0)
#define ETDM_COWORK_CON3_OUT1_USE_SINEGEN			BIT(29)
#define ETDM_COWORK_CON3_OUT2_USE_SINEGEN			BIT(30)

#define UL_REORDER_START_DATA(x)		(((x) & 0xf) << 8)
#define UL_REORDER_NO_BYPASS			BIT(6)
#define UL_REORDER_EN				BIT(4)
#define UL_REORDER_CHANNEL(x)			(((x) - 1))
#define UL_REORDER_CTRL_MASK			(0xfef)

#define ETDM_CON0_CH_NUM(x)			(((x) - 1) << 23)
#define ETDM_CON0_WORD_LEN(x)			(((x) - 1) << 16)
#define ETDM_CON0_BIT_LEN(x)			(((x) - 1) << 11)
#define ETDM_CON0_FORMAT(x)			((x) << 6)
#define ETDM_CON0_MASTER_LRCK_INV		BIT(30)
#define ETDM_CON0_MASTER_BCK_INV		BIT(29)
#define ETDM_CON0_SLAVE_LRCK_INV		BIT(28)
#define ETDM_CON0_SLAVE_BCK_INV			BIT(27)
#define ETDM_CON0_SLAVE_MODE			BIT(5)
#define ETDM_CON0_LOW_POWER_MODE		BIT(2)
#define ETDM_CON0_SYNC_MODE			BIT(1)

#define ETDM_CON1_MCLK_OUTPUT			BIT(16)
#define ETDM_CON1_LRCK_MANUAL_MODE		(0 << 29)
#define ETDM_CON1_LRCK_AUTO_MODE		(1 << 29)
#define ETDM_CON1_BCK_FROM_DIVIDER		BIT(30)

#define ETDM_CON4_ASYNC_RESET			BIT(11)

#define ETDM_IN_CON0_CTRL_MASK			(0x7f9ff9e2)
#define ETDM_IN_CON1_CTRL_MASK			(0x7ff10000)
#define ETDM_IN_CON2_CTRL_MASK			(0x840f801f)
#define ETDM_IN_CON3_CTRL_MASK			(0x7c000000)

#define ETDM_IN_CON1_LRCK_WIDTH(x)		(((x) - 1) << 20)
#define ETDM_IN_CON2_MULTI_IP_CH(x)		(((x) - 1) << 15)
#define ETDM_IN_CON2_MULTI_IP_2CH_MODE		BIT(31)
#define ETDM_IN_CON2_UPDATE_POINT_AUTO_DIS	(0 << 26)
#define ETDM_IN_CON2_UPDATE_POINT_AUTO_EN	(1 << 26)
#define ETDM_IN_CON2_UPDATE_POINT(x)		((x) & 0x1f)
#define ETDM_IN_CON3_FS(x)			(((x) & 0x1f) << 26)

#define ETDM_OUT_CON0_CTRL_MASK			(0x7f9ff9e2)
#define ETDM_OUT_CON1_CTRL_MASK			(0x7ff90000)
#define ETDM_OUT_CON4_CTRL_MASK			(0x1f)

#define ETDM_OUT_CON1_LRCK_WIDTH(x)		(((x) - 1) << 19)
#define ETDM_OUT_CON4_FS(x)			(((x) & 0x1f) << 0)
#define ETDM_OUT_CON4_CONN_FS(x)		(((x) & 0x1f) << 24)

/* ETDM_OUT2_CON4 (0x23b0) */
#define ETDM_OUT_CON4_INTERCONN_EN_SEL_MASK	(0x1f000000)

#define BLOCK_DPIDLE_REG			0x628
#define BLOCK_DPIDLE_REG_BIT			31
#define BLOCK_DPIDLE_REG_MASK			(1 << BLOCK_DPIDLE_REG_BIT)
#define BLOCK_DPIDLE_REG_BIT_ON			(1 << BLOCK_DPIDLE_REG_BIT)
#define BLOCK_DPIDLE_REG_BIT_OFF		(0 << BLOCK_DPIDLE_REG_BIT)

#endif
