
ccflags-y += -I$(srctree)/drivers/misc/mediatek/video/$(CONFIG_MTK_VIDEO_PLATFORM)/dispsys \
             -I$(srctree)/drivers/misc/mediatek/hdmi/hdmitx/$(CONFIG_MTK_VIDEO_PLATFORM)/inc	\
             -I$(srctree)/include	\
             -I$(srctree)/include/linux/soc/mediatek \

obj-y += p2i_hal.o

# EOF
