#
# Copyright (C) 2017 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ifneq ($(CONFIG_MT8188_STATIC_POWER),)
	obj-$(CONFIG_MT8188_STATIC_POWER) += mt8188_static_power.o
else
	obj-$(CONFIG_MTK_STATIC_POWER) += mtk_static_power.o
endif
