/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
 */

#ifndef __MT8696_COND_H__
#define __MT8696_COND_H__

/* Definition about SPM_COND_CHECK_BLOCKED
 * bit [00 ~ 15]: cg blocking index
 * bit [16 ~ 29]: pll blocking index
 * bit [30]     : pll blocking information
 * bit [31]    : idle condition check fail
 */

#define SPM_COND_BLOCKED_CG_IDX		(0)
#define SPM_COND_BLOCKED_PLL_IDX	(16)
#define SPM_COND_BLOCKED_PLL		(1<<30L)
#define SPM_COND_CHECK_FAIL		(1<<31L)

enum PLAT_SPM_COND {
	PLAT_SPM_COND_MTCMOS1 = 0,
	PLAT_INFRA_SW_CG0,
	PLAT_INFRA_SW_CG1,
	PLAT_MMSYS_CG_CON0,
	PLAT_MMSYS_CG_CON1,
	PLAT_AUDIO_IPSYS_CG0,
	PLAT_NNA_CG_0,
	PLAT_NNA_CG_1,
	PLAT_PERISYS_CG0,
	PLAT_PERISYS_CG1,
	PLAT_PERISYS_CG2,
	PLAT_RV33_CG,
	PLAT_VDEC_CG_0,
	PLAT_VDEC_CG_1,
	PLAT_VDEC_CG_2,
	PLAT_VDEC_CG_3,
	PLAT_VDEC_CG_4,
	PLAT_VDEC_CG_5,
	PLAT_VENC_CG_0,
	PLAT_SPM_COND_MAX,
};

enum PLAT_SPM_PLL_COND {
	PLAT_SPM_COND_UNIVPLL = 0,
	PLAT_SPM_COND_MFGPLL,
	PLAT_SPM_COND_MSDCPLL,
	PLAT_SPM_COND_TVPLL,
	PLAT_SPM_COND_MMPLL,
	PLAT_SPM_COND_PLL_MAX,
};

#endif
