ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/activity_sensor
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
obj-y	:=  activityhub.o

