# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_EINT_MTK)		+= mtk-eint.o
obj-$(CONFIG_PINCTRL_MTK)	+= pinctrl-mtk-common.o
obj-$(CONFIG_PINCTRL_MTK_V2)	+= pinctrl-mtk-common-v2.o
obj-$(CONFIG_PINCTRL_MTK_MOORE) += pinctrl-moore.o
obj-$(CONFIG_PINCTRL_MTK_PARIS) += pinctrl-paris.o pinctrl-mtk-common-v2_debug.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT8696)	+= pinctrl-mt8696.o
obj-$(CONFIG_PINCTRL_MT6397)	+= pinctrl-mt6397.o
