/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2020 MediaTek Inc.
 * Author: Guodong Liu <Guodong.Liu@mediatek.com>
 *
 */

#ifndef __PINCTRL_MTK_MT8696_H
#define __PINCTRL_MTK_MT8696_H

#include "pinctrl-paris.h"


static const struct mtk_pin_desc mtk_pins_mt8696[] = {

	MTK_PIN(
		0, "GPIO0",
		MTK_EINT_FUNCTION(0, 11),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO0"),
		MTK_FUNCTION(1, "EINT0"),
		MTK_FUNCTION(3, "SDA1"),
		MTK_FUNCTION(4, "NOR_SPI_IO0"),
		MTK_FUNCTION(7, "DBG_MON_A16")
	),

	MTK_PIN(
		1, "GPIO1",
		MTK_EINT_FUNCTION(0, 12),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO1"),
		MTK_FUNCTION(1, "EINT1"),
		MTK_FUNCTION(3, "SCL1"),
		MTK_FUNCTION(4, "NOR_SPI_CK"),
		MTK_FUNCTION(7, "DBG_MON_A17")
	),

	MTK_PIN(
		2, "GPIO2",
		MTK_EINT_FUNCTION(0, 13),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO2"),
		MTK_FUNCTION(1, "EINT2"),
		MTK_FUNCTION(4, "PWM2"),
		MTK_FUNCTION(5, "CLKM1"),
		MTK_FUNCTION(6, "SPI_IO3"),
		MTK_FUNCTION(7, "DBG_MON_B1")
	),

	MTK_PIN(
		3, "GPIO3",
		MTK_EINT_FUNCTION(0, 14),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO3"),
		MTK_FUNCTION(1, "EINT3"),
		MTK_FUNCTION(2, "DMIC_DAT7"),
		MTK_FUNCTION(4, "GBE_CRS"),
		MTK_FUNCTION(5, "CLKM0"),
		MTK_FUNCTION(6, "SPI_IO2"),
		MTK_FUNCTION(7, "DBG_MON_B0")
	),

	MTK_PIN(
		4, "GPIO4",
		MTK_EINT_FUNCTION(0, 15),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO4"),
		MTK_FUNCTION(1, "SRCCLKENA1")
	),

	MTK_PIN(
		5, "GPIO5",
		MTK_EINT_FUNCTION(0, 16),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO5"),
		MTK_FUNCTION(1, "I2SO0_MCK"),
		MTK_FUNCTION(2, "SPLIN_MCK"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_BCK"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_BCK"),
		MTK_FUNCTION(7, "DBG_MON_A3")
	),

	MTK_PIN(
		6, "GPIO6",
		MTK_EINT_FUNCTION(0, 17),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO6"),
		MTK_FUNCTION(1, "I2SO0_DATA0"),
		MTK_FUNCTION(2, "SPLIN_D0"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_DATA1"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_DATA1"),
		MTK_FUNCTION(7, "DBG_MON_A5")
	),

	MTK_PIN(
		7, "GPIO7",
		MTK_EINT_FUNCTION(0, 18),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO7"),
		MTK_FUNCTION(1, "I2SO0_BCK"),
		MTK_FUNCTION(2, "SPLIN_LRCK"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_LRCK"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_LRCK"),
		MTK_FUNCTION(7, "DBG_MON_A4")
	),

	MTK_PIN(
		8, "GPIO8",
		MTK_EINT_FUNCTION(0, 19),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO8"),
		MTK_FUNCTION(1, "I2SO0_LRCK"),
		MTK_FUNCTION(2, "SPLIN_BCK"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_DATA0"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_DATA0")
	),

	MTK_PIN(
		9, "GPIO9",
		MTK_EINT_FUNCTION(0, 20),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO9"),
		MTK_FUNCTION(1, "I2SO1_DATA2"),
		MTK_FUNCTION(2, "I2SO0_DATA2"),
		MTK_FUNCTION(3, "I2SO1_DATA3")
	),

	MTK_PIN(
		10, "GPIO10",
		MTK_EINT_FUNCTION(0, 21),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO10"),
		MTK_FUNCTION(1, "I2SO1_DATA3"),
		MTK_FUNCTION(2, "I2SO0_DATA3"),
		MTK_FUNCTION(3, "I2SO1_DATA4")
	),

	MTK_PIN(
		11, "GPIO11",
		MTK_EINT_FUNCTION(0, 22),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO11"),
		MTK_FUNCTION(1, "I2SO1_DATA4"),
		MTK_FUNCTION(3, "I2SO1_DATA5")
	),

	MTK_PIN(
		12, "GPIO12",
		MTK_EINT_FUNCTION(0, 23),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO12"),
		MTK_FUNCTION(1, "I2SO1_DATA5"),
		MTK_FUNCTION(2, "SPLIN_D0")
	),

	MTK_PIN(
		13, "GPIO13",
		MTK_EINT_FUNCTION(0, 24),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO13"),
		MTK_FUNCTION(1, "I2SO1_DATA6"),
		MTK_FUNCTION(2, "SPLIN_LRCK"),
		MTK_FUNCTION(5, "SCL0")
	),

	MTK_PIN(
		14, "GPIO14",
		MTK_EINT_FUNCTION(0, 25),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO14"),
		MTK_FUNCTION(1, "I2SO1_DATA7"),
		MTK_FUNCTION(2, "SPLIN_BCK"),
		MTK_FUNCTION(5, "SDA0")
	),

	MTK_PIN(
		15, "GPIO15",
		MTK_EINT_FUNCTION(0, 26),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO15"),
		MTK_FUNCTION(1, "I2SO1_DATA8"),
		MTK_FUNCTION(2, "SPLIN_MCK"),
		MTK_FUNCTION(5, "SDA1")
	),

	MTK_PIN(
		16, "GPIO16",
		MTK_EINT_FUNCTION(0, 27),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO16"),
		MTK_FUNCTION(1, "I2SO1_DATA9"),
		MTK_FUNCTION(2, "SPLIN_D1"),
		MTK_FUNCTION(3, "PCIE_CLKREQ_N"),
		MTK_FUNCTION(5, "SCL1")
	),

	MTK_PIN(
		17, "GPIO17",
		MTK_EINT_FUNCTION(0, 28),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO17"),
		MTK_FUNCTION(1, "I2SO1_DATA10"),
		MTK_FUNCTION(2, "SPLIN_D2"),
		MTK_FUNCTION(3, "PCIE_PERESET_N"),
		MTK_FUNCTION(5, "SDA2")
	),

	MTK_PIN(
		18, "GPIO18",
		MTK_EINT_FUNCTION(0, 29),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO18"),
		MTK_FUNCTION(1, "I2SO1_DATA11"),
		MTK_FUNCTION(2, "SPLIN_D3"),
		MTK_FUNCTION(3, "PCIE_WAKE_N"),
		MTK_FUNCTION(4, "IR_IN"),
		MTK_FUNCTION(5, "SCL2")
	),

	MTK_PIN(
		19, "GPIO19",
		MTK_EINT_FUNCTION(0, 30),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO19"),
		MTK_FUNCTION(1, "I2SO0_DATA1"),
		MTK_FUNCTION(2, "SPLIN_D1"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_DATA2"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_DATA2"),
		MTK_FUNCTION(7, "DBG_MON_A6")
	),

	MTK_PIN(
		20, "GPIO20",
		MTK_EINT_FUNCTION(0, 31),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO20"),
		MTK_FUNCTION(1, "I2SO0_DATA2"),
		MTK_FUNCTION(2, "SPLIN_D2"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_DATA3"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_DATA3"),
		MTK_FUNCTION(7, "DBG_MON_A7")
	),

	MTK_PIN(
		21, "GPIO21",
		MTK_EINT_FUNCTION(0, 32),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO21"),
		MTK_FUNCTION(1, "I2SO0_DATA3"),
		MTK_FUNCTION(2, "SPLIN_D3"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_DATA4"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_DATA4"),
		MTK_FUNCTION(5, "IR_IN"),
		MTK_FUNCTION(7, "DBG_MON_A8")
	),

	MTK_PIN(
		22, "GPIO22",
		MTK_EINT_FUNCTION(0, 33),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO22"),
		MTK_FUNCTION(1, "TDMIN_BCK"),
		MTK_FUNCTION(2, "USB_DRV"),
		MTK_FUNCTION(3, "SPLIN_MCK"),
		MTK_FUNCTION(4, "DMIC_CLK0"),
		MTK_FUNCTION(6, "I2SI0_MCK"),
		MTK_FUNCTION(7, "DBG_MON_A9")
	),

	MTK_PIN(
		23, "GPIO23",
		MTK_EINT_FUNCTION(0, 34),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO23"),
		MTK_FUNCTION(1, "TDMIN_DI"),
		MTK_FUNCTION(2, "USB_ID"),
		MTK_FUNCTION(3, "SPLIN_BCK"),
		MTK_FUNCTION(4, "DMIC_DAT0"),
		MTK_FUNCTION(5, "PWM3"),
		MTK_FUNCTION(6, "I2SI0_BCK"),
		MTK_FUNCTION(7, "DBG_MON_A10")
	),

	MTK_PIN(
		24, "GPIO24",
		MTK_EINT_FUNCTION(0, 35),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO24"),
		MTK_FUNCTION(1, "TDMIN_LRCK"),
		MTK_FUNCTION(3, "SPLIN_LRCK"),
		MTK_FUNCTION(4, "DMIC_DAT1"),
		MTK_FUNCTION(5, "PWM1"),
		MTK_FUNCTION(6, "I2SI0_LRCK"),
		MTK_FUNCTION(7, "DBG_MON_A11")
	),

	MTK_PIN(
		25, "GPIO25",
		MTK_EINT_FUNCTION(0, 36),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO25"),
		MTK_FUNCTION(1, "TDMIN_MCLK"),
		MTK_FUNCTION(3, "SPLIN_D0"),
		MTK_FUNCTION(5, "PWM2"),
		MTK_FUNCTION(6, "I2SI0_D0"),
		MTK_FUNCTION(7, "DBG_MON_A12")
	),

	MTK_PIN(
		26, "GPIO26",
		MTK_EINT_FUNCTION(0, 37),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO26"),
		MTK_FUNCTION(1, "USB_ID"),
		MTK_FUNCTION(2, "IR_IN"),
		MTK_FUNCTION(3, "JTRST_B_ICE"),
		MTK_FUNCTION(6, "RV33_JTAG_TRSTN")
	),

	MTK_PIN(
		27, "GPIO27",
		MTK_EINT_FUNCTION(0, 38),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO27"),
		MTK_FUNCTION(1, "USB_DRV")
	),

	MTK_PIN(
		28, "GPIO28",
		MTK_EINT_FUNCTION(0, 39),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO28"),
		MTK_FUNCTION(1, "PCIE_CLKREQ_N"),
		MTK_FUNCTION(2, "USB_ID"),
		MTK_FUNCTION(3, "AUDIO1_HDMI_OUT_DATA5"),
		MTK_FUNCTION(4, "AUDIO2_HDMI_OUT_DATA5"),
		MTK_FUNCTION(6, "I2SI0_D1"),
		MTK_FUNCTION(7, "DBG_MON_A13")
	),

	MTK_PIN(
		29, "GPIO29",
		MTK_EINT_FUNCTION(0, 40),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO29"),
		MTK_FUNCTION(1, "PCIE_PERESET_N"),
		MTK_FUNCTION(2, "USB_DRV"),
		MTK_FUNCTION(3, "SDA3"),
		MTK_FUNCTION(6, "I2SI0_D2"),
		MTK_FUNCTION(7, "DBG_MON_A14")
	),

	MTK_PIN(
		30, "GPIO30",
		MTK_EINT_FUNCTION(0, 41),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO30"),
		MTK_FUNCTION(1, "PCIE_WAKE_N"),
		MTK_FUNCTION(3, "SCL3"),
		MTK_FUNCTION(6, "I2SI0_D3"),
		MTK_FUNCTION(7, "DBG_MON_A15")
	),

	MTK_PIN(
		31, "GPIO31",
		MTK_EINT_FUNCTION(0, 42),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO31"),
		MTK_FUNCTION(1, "I2SO1_BCK"),
		MTK_FUNCTION(2, "I2SO0_BCK")
	),

	MTK_PIN(
		32, "GPIO32",
		MTK_EINT_FUNCTION(0, 43),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO32"),
		MTK_FUNCTION(1, "I2SO1_LRCK"),
		MTK_FUNCTION(2, "I2SO0_LRCK"),
		MTK_FUNCTION(3, "I2SO1_DATA0")
	),

	MTK_PIN(
		33, "GPIO33",
		MTK_EINT_FUNCTION(0, 44),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO33"),
		MTK_FUNCTION(1, "I2SO1_MCK"),
		MTK_FUNCTION(2, "I2SO0_MCK")
	),

	MTK_PIN(
		34, "GPIO34",
		MTK_EINT_FUNCTION(0, 45),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO34"),
		MTK_FUNCTION(1, "I2SO1_DATA0"),
		MTK_FUNCTION(2, "I2SO0_DATA0"),
		MTK_FUNCTION(3, "I2SO1_DATA1")
	),

	MTK_PIN(
		35, "GPIO35",
		MTK_EINT_FUNCTION(0, 46),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO35"),
		MTK_FUNCTION(1, "PCM1_TX"),
		MTK_FUNCTION(2, "PCM2_TX"),
		MTK_FUNCTION(5, "CLKM0"),
		MTK_FUNCTION(7, "DBG_MON_A18")
	),

	MTK_PIN(
		36, "GPIO36",
		MTK_EINT_FUNCTION(0, 47),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO36"),
		MTK_FUNCTION(1, "PCM1_CLK"),
		MTK_FUNCTION(2, "PCM2_CLK"),
		MTK_FUNCTION(5, "CLKM1"),
		MTK_FUNCTION(7, "DBG_MON_A19")
	),

	MTK_PIN(
		37, "GPIO37",
		MTK_EINT_FUNCTION(0, 48),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO37"),
		MTK_FUNCTION(1, "PCM1_RX"),
		MTK_FUNCTION(2, "PCM2_RX"),
		MTK_FUNCTION(5, "CLKM2"),
		MTK_FUNCTION(7, "DBG_MON_A20")
	),

	MTK_PIN(
		38, "GPIO38",
		MTK_EINT_FUNCTION(0, 49),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO38"),
		MTK_FUNCTION(1, "PCM1_SYNC"),
		MTK_FUNCTION(2, "PCM2_SYNC"),
		MTK_FUNCTION(5, "CLKM3"),
		MTK_FUNCTION(7, "DBG_MON_A21")
	),

	MTK_PIN(
		39, "GPIO39",
		MTK_EINT_FUNCTION(0, 50),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO39"),
		MTK_FUNCTION(1, "I2SI0_D3"),
		MTK_FUNCTION(2, "SPLIN_D3"),
		MTK_FUNCTION(3, "DMIC_DAT3")
	),

	MTK_PIN(
		40, "GPIO40",
		MTK_EINT_FUNCTION(0, 51),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO40"),
		MTK_FUNCTION(1, "MSDC2_CLK"),
		MTK_FUNCTION(7, "DBG_MON_A26")
	),

	MTK_PIN(
		41, "GPIO41",
		MTK_EINT_FUNCTION(0, 52),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO41"),
		MTK_FUNCTION(1, "MSDC2_DSL"),
		MTK_FUNCTION(7, "DBG_MON_A27")
	),

	MTK_PIN(
		42, "GPIO42",
		MTK_EINT_FUNCTION(0, 53),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO42"),
		MTK_FUNCTION(1, "MSDC2_DAT3"),
		MTK_FUNCTION(7, "DBG_MON_A28")
	),

	MTK_PIN(
		43, "GPIO43",
		MTK_EINT_FUNCTION(0, 54),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO43"),
		MTK_FUNCTION(1, "MSDC2_DAT2"),
		MTK_FUNCTION(7, "DBG_MON_A29")
	),

	MTK_PIN(
		44, "GPIO44",
		MTK_EINT_FUNCTION(0, 55),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO44"),
		MTK_FUNCTION(1, "MSDC2_DAT1"),
		MTK_FUNCTION(7, "DBG_MON_A30")
	),

	MTK_PIN(
		45, "GPIO45",
		MTK_EINT_FUNCTION(0, 56),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO45"),
		MTK_FUNCTION(1, "MSDC2_DAT0"),
		MTK_FUNCTION(7, "DBG_MON_A31")
	),

	MTK_PIN(
		46, "GPIO46",
		MTK_EINT_FUNCTION(0, 57),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO46"),
		MTK_FUNCTION(1, "MSDC2_CMD"),
		MTK_FUNCTION(7, "DBG_MON_A32")
	),

	MTK_PIN(
		47, "GPIO47",
		MTK_EINT_FUNCTION(0, 58),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO47"),
		MTK_FUNCTION(1, "MSDC0_DSL"),
		MTK_FUNCTION(2, "PWM6_AO"),
		MTK_FUNCTION(4, "DMIC_CLK2"),
		MTK_FUNCTION(5, "SPI_CK_0"),
		MTK_FUNCTION(6, "TDMIN_BCK")
	),

	MTK_PIN(
		48, "GPIO48",
		MTK_EINT_FUNCTION(0, 59),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO48"),
		MTK_FUNCTION(1, "MSDC0_CLK"),
		MTK_FUNCTION(2, "PWM7_AO"),
		MTK_FUNCTION(4, "DMIC_DAT4"),
		MTK_FUNCTION(5, "SPI_MI_0"),
		MTK_FUNCTION(6, "TDMIN_DI")
	),

	MTK_PIN(
		49, "GPIO49",
		MTK_EINT_FUNCTION(0, 60),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO49"),
		MTK_FUNCTION(1, "MSDC0_DAT7"),
		MTK_FUNCTION(4, "DMIC_DAT5"),
		MTK_FUNCTION(5, "SPI_CS_0"),
		MTK_FUNCTION(6, "TDMIN_LRCK")
	),

	MTK_PIN(
		50, "GPIO50",
		MTK_EINT_FUNCTION(0, 61),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO50"),
		MTK_FUNCTION(1, "MSDC0_DAT6"),
		MTK_FUNCTION(4, "DMIC_CLK3"),
		MTK_FUNCTION(5, "SPI_MO_0"),
		MTK_FUNCTION(6, "TDMIN_MCLK")
	),

	MTK_PIN(
		51, "GPIO51",
		MTK_EINT_FUNCTION(0, 62),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO51"),
		MTK_FUNCTION(1, "MSDC0_DAT5"),
		MTK_FUNCTION(4, "DMIC_DAT6"),
		MTK_FUNCTION(6, "SPLIN_MCK")
	),

	MTK_PIN(
		52, "GPIO52",
		MTK_EINT_FUNCTION(0, 63),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO52"),
		MTK_FUNCTION(1, "MSDC0_DAT4"),
		MTK_FUNCTION(4, "DMIC_DAT7"),
		MTK_FUNCTION(6, "SPLIN_BCK")
	),

	MTK_PIN(
		53, "GPIO53",
		MTK_EINT_FUNCTION(0, 64),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO53"),
		MTK_FUNCTION(1, "MSDC0_DAT3"),
		MTK_FUNCTION(3, "NAND_SPI_IO0"),
		MTK_FUNCTION(4, "DMIC_CLK0"),
		MTK_FUNCTION(6, "SPLIN_D0")
	),

	MTK_PIN(
		54, "GPIO54",
		MTK_EINT_FUNCTION(0, 65),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO54"),
		MTK_FUNCTION(1, "MSDC0_DAT2"),
		MTK_FUNCTION(3, "NAND_SPI_IO1"),
		MTK_FUNCTION(4, "DMIC_DAT0"),
		MTK_FUNCTION(6, "SPLIN_D1")
	),

	MTK_PIN(
		55, "GPIO55",
		MTK_EINT_FUNCTION(0, 66),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO55"),
		MTK_FUNCTION(1, "MSDC0_DAT1"),
		MTK_FUNCTION(3, "NAND_SPI_IO2"),
		MTK_FUNCTION(4, "DMIC_DAT1"),
		MTK_FUNCTION(6, "SPLIN_D2")
	),

	MTK_PIN(
		56, "GPIO56",
		MTK_EINT_FUNCTION(0, 67),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO56"),
		MTK_FUNCTION(1, "MSDC0_DAT0"),
		MTK_FUNCTION(3, "NAND_SPI_IO3"),
		MTK_FUNCTION(4, "DMIC_CLK1"),
		MTK_FUNCTION(6, "SPLIN_D3")
	),

	MTK_PIN(
		57, "GPIO57",
		MTK_EINT_FUNCTION(0, 68),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO57"),
		MTK_FUNCTION(1, "MSDC0_CMD"),
		MTK_FUNCTION(3, "NAND_SPI_CS"),
		MTK_FUNCTION(4, "DMIC_DAT2"),
		MTK_FUNCTION(6, "SPLIN_LRCK")
	),

	MTK_PIN(
		58, "GPIO58",
		MTK_EINT_FUNCTION(0, 69),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO58"),
		MTK_FUNCTION(1, "MSDC0_RSTB"),
		MTK_FUNCTION(3, "NAND_SPI_CK"),
		MTK_FUNCTION(4, "DMIC_DAT3")
	),

	MTK_PIN(
		59, "GPIO59",
		MTK_EINT_FUNCTION(0, 70),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO59"),
		MTK_FUNCTION(1, "JTDO_ICE"),
		MTK_FUNCTION(2, "DMIC_CLK2"),
		MTK_FUNCTION(3, "SPM2BUCK0"),
		MTK_FUNCTION(4, "JTDO_SPM"),
		MTK_FUNCTION(5, "EINT3")
	),

	MTK_PIN(
		60, "GPIO60",
		MTK_EINT_FUNCTION(0, 71),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO60"),
		MTK_FUNCTION(1, "JTMS_ICE"),
		MTK_FUNCTION(2, "DMIC_DAT4"),
		MTK_FUNCTION(3, "SPM2BUCK1"),
		MTK_FUNCTION(4, "JTMS_SPM"),
		MTK_FUNCTION(5, "EINT2")
	),

	MTK_PIN(
		61, "GPIO61",
		MTK_EINT_FUNCTION(0, 72),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO61"),
		MTK_FUNCTION(1, "JTCK_ICE"),
		MTK_FUNCTION(2, "DMIC_DAT5"),
		MTK_FUNCTION(4, "JTCK_SPM")
	),

	MTK_PIN(
		62, "GPIO62",
		MTK_EINT_FUNCTION(0, 73),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO62"),
		MTK_FUNCTION(1, "JTDI_ICE"),
		MTK_FUNCTION(2, "DMIC_CLK3"),
		MTK_FUNCTION(4, "JTDI_SPM"),
		MTK_FUNCTION(6, "SPI_CS")
	),

	MTK_PIN(
		63, "GPIO63",
		MTK_EINT_FUNCTION(0, 74),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO63"),
		MTK_FUNCTION(1, "JTRST_B_ICE"),
		MTK_FUNCTION(2, "DMIC_DAT6"),
		MTK_FUNCTION(3, "IR_IN"),
		MTK_FUNCTION(4, "JTRST_B_SPM"),
		MTK_FUNCTION(6, "SPI_CK")
	),

	MTK_PIN(
		64, "GPIO64",
		MTK_EINT_FUNCTION(0, 75),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO64"),
		MTK_FUNCTION(1, "KPROW0"),
		MTK_FUNCTION(3, "UCTS0"),
		MTK_FUNCTION(7, "DBG_MON_B4")
	),

	MTK_PIN(
		65, "GPIO65",
		MTK_EINT_FUNCTION(0, 76),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO65"),
		MTK_FUNCTION(1, "KPROW1"),
		MTK_FUNCTION(3, "URTS0"),
		MTK_FUNCTION(7, "DBG_MON_B5")
	),

	MTK_PIN(
		66, "GPIO66",
		MTK_EINT_FUNCTION(0, 77),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO66"),
		MTK_FUNCTION(1, "KPROW2")
	),

	MTK_PIN(
		67, "GPIO67",
		MTK_EINT_FUNCTION(0, 78),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO67"),
		MTK_FUNCTION(1, "KPCOL0"),
		MTK_FUNCTION(2, "UTXD1"),
		MTK_FUNCTION(3, "UTXD0"),
		MTK_FUNCTION(7, "DBG_MON_B6")
	),

	MTK_PIN(
		68, "GPIO68",
		MTK_EINT_FUNCTION(0, 79),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO68"),
		MTK_FUNCTION(1, "KPCOL1"),
		MTK_FUNCTION(2, "URXD1"),
		MTK_FUNCTION(3, "URXD0"),
		MTK_FUNCTION(7, "DBG_MON_B7")
	),

	MTK_PIN(
		69, "GPIO69",
		MTK_EINT_FUNCTION(0, 80),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO69"),
		MTK_FUNCTION(1, "KPCOL2")
	),

	MTK_PIN(
		70, "GPIO70",
		MTK_EINT_FUNCTION(0, 81),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO70"),
		MTK_FUNCTION(1, "WATCHDOG")
	),

	MTK_PIN(
		71, "GPIO71",
		MTK_EINT_FUNCTION(0, 82),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO71"),
		MTK_FUNCTION(1, "SDA4_AO"),
		MTK_FUNCTION(2, "PWM4"),
		MTK_FUNCTION(3, "PWM6_AO")
	),

	MTK_PIN(
		72, "GPIO72",
		MTK_EINT_FUNCTION(0, 83),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO72"),
		MTK_FUNCTION(1, "SCL4_AO"),
		MTK_FUNCTION(2, "PWM5"),
		MTK_FUNCTION(3, "PWM7_AO")
	),

	MTK_PIN(
		73, "GPIO73",
		MTK_EINT_FUNCTION(0, 84),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO73"),
		MTK_FUNCTION(1, "SCL3"),
		MTK_FUNCTION(2, "PWM6_AO"),
		MTK_FUNCTION(3, "URXD2"),
		MTK_FUNCTION(4, "SPM2BUCK0")
	),

	MTK_PIN(
		74, "GPIO74",
		MTK_EINT_FUNCTION(0, 85),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO74"),
		MTK_FUNCTION(1, "SDA3"),
		MTK_FUNCTION(2, "PWM7_AO"),
		MTK_FUNCTION(3, "UTXD2"),
		MTK_FUNCTION(4, "SPM2BUCK1")
	),

	MTK_PIN(
		75, "GPIO75",
		MTK_EINT_FUNCTION(0, 86),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO75"),
		MTK_FUNCTION(1, "SPDIF_OUT"),
		MTK_FUNCTION(2, "PCIE_CLKREQ_N"),
		MTK_FUNCTION(7, "DBG_MON_A0")
	),

	MTK_PIN(
		76, "GPIO76",
		MTK_EINT_FUNCTION(0, 87),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO76"),
		MTK_FUNCTION(1, "SPDIF_IN0"),
		MTK_FUNCTION(2, "PCIE_PERESET_N"),
		MTK_FUNCTION(3, "IR_IN"),
		MTK_FUNCTION(7, "DBG_MON_A1")
	),

	MTK_PIN(
		77, "GPIO77",
		MTK_EINT_FUNCTION(0, 88),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO77"),
		MTK_FUNCTION(1, "SPDIF_IN1"),
		MTK_FUNCTION(2, "PCIE_WAKE_N"),
		MTK_FUNCTION(6, "I2SO1_DATA3"),
		MTK_FUNCTION(7, "DBG_MON_A2")
	),

	MTK_PIN(
		78, "GPIO78",
		MTK_EINT_FUNCTION(0, 89),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO78"),
		MTK_FUNCTION(1, "SRCCLKENA0")
	),

	MTK_PIN(
		79, "GPIO79",
		MTK_EINT_FUNCTION(0, 90),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO79"),
		MTK_FUNCTION(1, "I2SO1_DATA1"),
		MTK_FUNCTION(2, "I2SO0_DATA1"),
		MTK_FUNCTION(3, "I2SO1_DATA2")
	),

	MTK_PIN(
		80, "GPIO80",
		MTK_EINT_FUNCTION(0, 91),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO80"),
		MTK_FUNCTION(1, "UCTS0"),
		MTK_FUNCTION(2, "URXD2"),
		MTK_FUNCTION(3, "JTDO_ICE"),
		MTK_FUNCTION(4, "NOR_SPI_CS"),
		MTK_FUNCTION(6, "RV33_JTAG_TDO"),
		MTK_FUNCTION(7, "DBG_MON_A22")
	),

	MTK_PIN(
		81, "GPIO81",
		MTK_EINT_FUNCTION(0, 92),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO81"),
		MTK_FUNCTION(1, "URTS0"),
		MTK_FUNCTION(2, "UTXD2"),
		MTK_FUNCTION(3, "JTDI_ICE"),
		MTK_FUNCTION(4, "NOR_SPI_IO1"),
		MTK_FUNCTION(6, "RV33_JTAG_TCK"),
		MTK_FUNCTION(7, "DBG_MON_A23")
	),

	MTK_PIN(
		82, "GPIO82",
		MTK_EINT_FUNCTION(0, 93),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO82"),
		MTK_FUNCTION(1, "URXD0"),
		MTK_FUNCTION(3, "JTMS_ICE"),
		MTK_FUNCTION(4, "NOR_SPI_IO2"),
		MTK_FUNCTION(6, "RV33_JTAG_TDI"),
		MTK_FUNCTION(7, "DBG_MON_A24")
	),

	MTK_PIN(
		83, "GPIO83",
		MTK_EINT_FUNCTION(0, 94),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO83"),
		MTK_FUNCTION(1, "UTXD0"),
		MTK_FUNCTION(3, "JTCK_ICE"),
		MTK_FUNCTION(4, "NOR_SPI_IO3"),
		MTK_FUNCTION(6, "RV33_JTAG_TMS"),
		MTK_FUNCTION(7, "DBG_MON_A25")
	),

	MTK_PIN(
		84, "GPIO84",
		MTK_EINT_FUNCTION(0, 95),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO84"),
		MTK_FUNCTION(1, "URXD1"),
		MTK_FUNCTION(2, "SDA2"),
		MTK_FUNCTION(3, "PWM2"),
		MTK_FUNCTION(4, "PWM6_AO"),
		MTK_FUNCTION(5, "SPM2BUCK0")
	),

	MTK_PIN(
		85, "GPIO85",
		MTK_EINT_FUNCTION(0, 96),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO85"),
		MTK_FUNCTION(1, "UTXD1"),
		MTK_FUNCTION(2, "SCL2"),
		MTK_FUNCTION(3, "PWM3"),
		MTK_FUNCTION(4, "PWM7_AO"),
		MTK_FUNCTION(5, "SPM2BUCK1")
	),

	MTK_PIN(
		86, "GPIO86",
		MTK_EINT_FUNCTION(0, 97),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO86"),
		MTK_FUNCTION(1, "NAND_ALE"),
		MTK_FUNCTION(2, "PWM0"),
		MTK_FUNCTION(3, "DMIC_CLK0"),
		MTK_FUNCTION(4, "PWM6_AO"),
		MTK_FUNCTION(5, "IR_IN"),
		MTK_FUNCTION(6, "I2SO1_BCK")
	),

	MTK_PIN(
		87, "GPIO87",
		MTK_EINT_FUNCTION(0, 98),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO87"),
		MTK_FUNCTION(1, "NAND_ND0"),
		MTK_FUNCTION(2, "PWM1"),
		MTK_FUNCTION(3, "DMIC_DAT0"),
		MTK_FUNCTION(4, "SPI_CK"),
		MTK_FUNCTION(6, "I2SO1_LRCK")
	),

	MTK_PIN(
		88, "GPIO88",
		MTK_EINT_FUNCTION(0, 99),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO88"),
		MTK_FUNCTION(1, "NAND_ND1"),
		MTK_FUNCTION(2, "SPDIF_OUT"),
		MTK_FUNCTION(3, "DMIC_DAT1"),
		MTK_FUNCTION(4, "SPI_IO2"),
		MTK_FUNCTION(6, "I2SO1_MCK")
	),

	MTK_PIN(
		89, "GPIO89",
		MTK_EINT_FUNCTION(0, 100),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO89"),
		MTK_FUNCTION(1, "NAND_ND2"),
		MTK_FUNCTION(2, "SPDIF_IN0"),
		MTK_FUNCTION(3, "DMIC_CLK1"),
		MTK_FUNCTION(4, "SPI_IO3"),
		MTK_FUNCTION(6, "I2SO1_DATA0")
	),

	MTK_PIN(
		90, "GPIO90",
		MTK_EINT_FUNCTION(0, 101),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO90"),
		MTK_FUNCTION(1, "NAND_ND3"),
		MTK_FUNCTION(2, "SPDIF_IN1"),
		MTK_FUNCTION(3, "DMIC_DAT2"),
		MTK_FUNCTION(4, "SPI_IO0"),
		MTK_FUNCTION(6, "I2SO1_DATA1")
	),

	MTK_PIN(
		91, "GPIO91",
		MTK_EINT_FUNCTION(0, 102),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO91"),
		MTK_FUNCTION(1, "NAND_ND4"),
		MTK_FUNCTION(3, "DMIC_DAT3"),
		MTK_FUNCTION(4, "SPI_IO1"),
		MTK_FUNCTION(5, "PWM7_AO"),
		MTK_FUNCTION(6, "I2SO1_DATA2")
	),

	MTK_PIN(
		92, "GPIO92",
		MTK_EINT_FUNCTION(0, 103),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO92"),
		MTK_FUNCTION(1, "NAND_ND5"),
		MTK_FUNCTION(3, "DMIC_CLK2"),
		MTK_FUNCTION(5, "SPI_MI_0"),
		MTK_FUNCTION(6, "I2SO1_DATA3")
	),

	MTK_PIN(
		93, "GPIO93",
		MTK_EINT_FUNCTION(0, 104),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO93"),
		MTK_FUNCTION(1, "NAND_ND6"),
		MTK_FUNCTION(2, "NAND_SPI_IO0"),
		MTK_FUNCTION(3, "DMIC_DAT4"),
		MTK_FUNCTION(4, "NOR_SPI_IO0"),
		MTK_FUNCTION(5, "SPI_MO_0"),
		MTK_FUNCTION(6, "SPLIN_LRCK")
	),

	MTK_PIN(
		94, "GPIO94",
		MTK_EINT_FUNCTION(0, 105),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO94"),
		MTK_FUNCTION(1, "NAND_ND7"),
		MTK_FUNCTION(2, "NAND_SPI_IO1"),
		MTK_FUNCTION(3, "DMIC_DAT5"),
		MTK_FUNCTION(4, "NOR_SPI_IO1"),
		MTK_FUNCTION(5, "SPI_CK_0"),
		MTK_FUNCTION(6, "SPLIN_BCK")
	),

	MTK_PIN(
		95, "GPIO95",
		MTK_EINT_FUNCTION(0, 106),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO95"),
		MTK_FUNCTION(1, "NAND_WEB"),
		MTK_FUNCTION(2, "NAND_SPI_IO2"),
		MTK_FUNCTION(3, "DMIC_CLK3"),
		MTK_FUNCTION(4, "NOR_SPI_IO2"),
		MTK_FUNCTION(5, "SPI_CS_0"),
		MTK_FUNCTION(6, "SPLIN_MCK")
	),

	MTK_PIN(
		96, "GPIO96",
		MTK_EINT_FUNCTION(0, 107),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO96"),
		MTK_FUNCTION(1, "NAND_REB"),
		MTK_FUNCTION(2, "NAND_SPI_IO3"),
		MTK_FUNCTION(3, "DMIC_DAT6"),
		MTK_FUNCTION(4, "NOR_SPI_IO3"),
		MTK_FUNCTION(6, "SPLIN_D1")
	),

	MTK_PIN(
		97, "GPIO97",
		MTK_EINT_FUNCTION(0, 108),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO97"),
		MTK_FUNCTION(1, "NAND_RB"),
		MTK_FUNCTION(2, "NAND_SPI_CS"),
		MTK_FUNCTION(3, "DMIC_DAT7"),
		MTK_FUNCTION(5, "TDMIN_BCK"),
		MTK_FUNCTION(6, "SPLIN_D2")
	),

	MTK_PIN(
		98, "GPIO98",
		MTK_EINT_FUNCTION(0, 109),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO98"),
		MTK_FUNCTION(1, "NAND_CLE"),
		MTK_FUNCTION(2, "NAND_SPI_CK"),
		MTK_FUNCTION(3, "PWM2"),
		MTK_FUNCTION(4, "NOR_SPI_CK"),
		MTK_FUNCTION(5, "TDMIN_DI"),
		MTK_FUNCTION(6, "SPLIN_D3")
	),

	MTK_PIN(
		99, "GPIO99",
		MTK_EINT_FUNCTION(0, 110),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO99"),
		MTK_FUNCTION(1, "NAND_CEB1"),
		MTK_FUNCTION(2, "SDA2"),
		MTK_FUNCTION(3, "SDA1"),
		MTK_FUNCTION(4, "NOR_SPI_CS"),
		MTK_FUNCTION(5, "TDMIN_LRCK"),
		MTK_FUNCTION(6, "SPLIN_D0")
	),

	MTK_PIN(
		100, "GPIO100",
		MTK_EINT_FUNCTION(0, 111),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO100"),
		MTK_FUNCTION(1, "NAND_CEB0"),
		MTK_FUNCTION(2, "SCL2"),
		MTK_FUNCTION(3, "SCL1"),
		MTK_FUNCTION(4, "SPI_CS"),
		MTK_FUNCTION(5, "TDMIN_MCLK")
	),

	MTK_PIN(
		101, "GPIO101",
		MTK_EINT_FUNCTION(0, 112),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO101"),
		MTK_FUNCTION(1, "HDMIRX20_SCL")
	),

	MTK_PIN(
		102, "GPIO102",
		MTK_EINT_FUNCTION(0, 113),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO102"),
		MTK_FUNCTION(1, "HDMIRX20_SDA")
	),

	MTK_PIN(
		103, "GPIO103",
		MTK_EINT_FUNCTION(0, 114),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO103"),
		MTK_FUNCTION(1, "HDMIRX20_HTPLG")
	),

	MTK_PIN(
		104, "GPIO104",
		MTK_EINT_FUNCTION(0, 115),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO104"),
		MTK_FUNCTION(1, "SCL0")
	),

	MTK_PIN(
		105, "GPIO105",
		MTK_EINT_FUNCTION(0, 116),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO105"),
		MTK_FUNCTION(1, "SDA0")
	),

	MTK_PIN(
		106, "GPIO106",
		MTK_EINT_FUNCTION(0, 117),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO106"),
		MTK_FUNCTION(1, "SDA1")
	),

	MTK_PIN(
		107, "GPIO107",
		MTK_EINT_FUNCTION(0, 118),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO107"),
		MTK_FUNCTION(1, "SCL1")
	),

	MTK_PIN(
		108, "GPIO108",
		MTK_EINT_FUNCTION(0, 119),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO108"),
		MTK_FUNCTION(1, "SDA2")
	),

	MTK_PIN(
		109, "GPIO109",
		MTK_EINT_FUNCTION(0, 120),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO109"),
		MTK_FUNCTION(1, "SCL2")
	),

	MTK_PIN(
		110, "GPIO110",
		MTK_EINT_FUNCTION(0, 121),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO110"),
		MTK_FUNCTION(1, "HDMITX20_CEC")
	),

	MTK_PIN(
		111, "GPIO111",
		MTK_EINT_FUNCTION(0, 122),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO111"),
		MTK_FUNCTION(1, "HDMITX20_HTPLG")
	),

	MTK_PIN(
		112, "GPIO112",
		MTK_EINT_FUNCTION(0, 123),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO112"),
		MTK_FUNCTION(1, "HDMITX20_SCL")
	),

	MTK_PIN(
		113, "GPIO113",
		MTK_EINT_FUNCTION(0, 124),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO113"),
		MTK_FUNCTION(1, "HDMITX20_SDA")
	),

	MTK_PIN(
		114, "GPIO114",
		MTK_EINT_FUNCTION(0, 125),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO114"),
		MTK_FUNCTION(1, "SCL5")
	),

	MTK_PIN(
		115, "GPIO115",
		MTK_EINT_FUNCTION(0, 126),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO115"),
		MTK_FUNCTION(1, "SDA5"),
		MTK_FUNCTION(7, "DBG_MON_B32")
	),

	MTK_PIN(
		116, "GPIO116",
		MTK_EINT_FUNCTION(0, 127),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO116"),
		MTK_FUNCTION(1, "HDMIRX20_PWR5V")
	),

	MTK_PIN(
		117, "GPIO117",
		MTK_EINT_FUNCTION(0, 128),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO117"),
		MTK_FUNCTION(1, "URXD2"),
		MTK_FUNCTION(2, "MSDC1_DET"),
		MTK_FUNCTION(3, "SDA1"),
		MTK_FUNCTION(5, "SPM2BUCK0")
	),

	MTK_PIN(
		118, "GPIO118",
		MTK_EINT_FUNCTION(0, 129),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO118"),
		MTK_FUNCTION(1, "UTXD2"),
		MTK_FUNCTION(2, "MSDC1_PSW"),
		MTK_FUNCTION(3, "SCL1"),
		MTK_FUNCTION(5, "SPM2BUCK1")
	),

	MTK_PIN(
		119, "GPIO119",
		MTK_EINT_FUNCTION(0, 130),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO119"),
		MTK_FUNCTION(1, "DMIC_CLK0"),
		MTK_FUNCTION(2, "MCUPM_JTAG_TDO"),
		MTK_FUNCTION(5, "JTDO_SPM"),
		MTK_FUNCTION(6, "I2SI0_LRCK")
	),

	MTK_PIN(
		120, "GPIO120",
		MTK_EINT_FUNCTION(0, 131),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO120"),
		MTK_FUNCTION(1, "DMIC_DAT0"),
		MTK_FUNCTION(2, "MCUPM_JTAG_TMS"),
		MTK_FUNCTION(5, "JTMS_SPM"),
		MTK_FUNCTION(6, "I2SI0_D0")
	),

	MTK_PIN(
		121, "GPIO121",
		MTK_EINT_FUNCTION(0, 132),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO121"),
		MTK_FUNCTION(1, "DMIC_DAT1"),
		MTK_FUNCTION(2, "MCUPM_JTAG_TCK"),
		MTK_FUNCTION(5, "JTCK_SPM"),
		MTK_FUNCTION(6, "I2SI0_D1")
	),

	MTK_PIN(
		122, "GPIO122",
		MTK_EINT_FUNCTION(0, 133),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO122"),
		MTK_FUNCTION(1, "DMIC_CLK1"),
		MTK_FUNCTION(2, "MCUPM_JTAG_TDI"),
		MTK_FUNCTION(5, "JTDI_SPM"),
		MTK_FUNCTION(6, "I2SI0_BCK")
	),

	MTK_PIN(
		123, "GPIO123",
		MTK_EINT_FUNCTION(0, 134),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO123"),
		MTK_FUNCTION(1, "DMIC_DAT2"),
		MTK_FUNCTION(2, "MCUPM_JTAG_TRSTN"),
		MTK_FUNCTION(5, "JTRST_B_SPM"),
		MTK_FUNCTION(6, "I2SI0_D2")
	),

	MTK_PIN(
		124, "GPIO124",
		MTK_EINT_FUNCTION(0, 135),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO124"),
		MTK_FUNCTION(1, "DMIC_DAT3"),
		MTK_FUNCTION(2, "GBE_CRS"),
		MTK_FUNCTION(6, "I2SI0_D3")
	),

	MTK_PIN(
		125, "GPIO125",
		MTK_EINT_FUNCTION(0, 136),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO125"),
		MTK_FUNCTION(1, "I2SI0_LRCK"),
		MTK_FUNCTION(2, "SPLIN_LRCK"),
		MTK_FUNCTION(3, "DMIC_CLK0")
	),

	MTK_PIN(
		126, "GPIO126",
		MTK_EINT_FUNCTION(0, 137),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO126"),
		MTK_FUNCTION(1, "I2SI0_BCK"),
		MTK_FUNCTION(2, "SPLIN_BCK"),
		MTK_FUNCTION(3, "DMIC_CLK1")
	),

	MTK_PIN(
		127, "GPIO127",
		MTK_EINT_FUNCTION(0, 138),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO127"),
		MTK_FUNCTION(1, "I2SI0_MCK"),
		MTK_FUNCTION(2, "SPLIN_MCK")
	),

	MTK_PIN(
		128, "GPIO128",
		MTK_EINT_FUNCTION(0, 139),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO128"),
		MTK_FUNCTION(1, "I2SI0_D0"),
		MTK_FUNCTION(2, "SPLIN_D0"),
		MTK_FUNCTION(3, "DMIC_DAT0")
	),

	MTK_PIN(
		129, "GPIO129",
		MTK_EINT_FUNCTION(0, 140),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO129"),
		MTK_FUNCTION(1, "I2SI0_D1"),
		MTK_FUNCTION(2, "SPLIN_D1"),
		MTK_FUNCTION(3, "DMIC_DAT1")
	),

	MTK_PIN(
		130, "GPIO130",
		MTK_EINT_FUNCTION(0, 141),
		DRV_GRP0,
		MTK_FUNCTION(0, "GPIO130"),
		MTK_FUNCTION(1, "I2SI0_D2"),
		MTK_FUNCTION(2, "SPLIN_D2"),
		MTK_FUNCTION(3, "DMIC_DAT2")
	),

	MTK_PIN(
		131, "GPIO131",
		MTK_EINT_FUNCTION(0, 142),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO131"),
		MTK_FUNCTION(1, "MSDC1_DET"),
		MTK_FUNCTION(4, "mbistreaden_trigger"),
		MTK_FUNCTION(5, "CLKM2"),
		MTK_FUNCTION(6, "SPI_IO0"),
		MTK_FUNCTION(7, "DBG_MON_B2")
	),

	MTK_PIN(
		132, "GPIO132",
		MTK_EINT_FUNCTION(0, 143),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO132"),
		MTK_FUNCTION(1, "MSDC1_PSW"),
		MTK_FUNCTION(4, "mbistwriteen_trigger"),
		MTK_FUNCTION(5, "CLKM3"),
		MTK_FUNCTION(6, "SPI_IO1"),
		MTK_FUNCTION(7, "DBG_MON_B3")
	),

	MTK_PIN(
		133, "GPIO133",
		MTK_EINT_FUNCTION(0, 144),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO133"),
		MTK_FUNCTION(1, "GBE_TXD3"),
		MTK_FUNCTION(2, "SPLIN_MCK"),
		MTK_FUNCTION(3, "RV33_JTAG_TDO"),
		MTK_FUNCTION(7, "DBG_MON_B8")
	),

	MTK_PIN(
		134, "GPIO134",
		MTK_EINT_FUNCTION(0, 145),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO134"),
		MTK_FUNCTION(1, "GBE_TXD2"),
		MTK_FUNCTION(2, "SPLIN_LRCK"),
		MTK_FUNCTION(3, "RV33_JTAG_TMS"),
		MTK_FUNCTION(7, "DBG_MON_B9")
	),

	MTK_PIN(
		135, "GPIO135",
		MTK_EINT_FUNCTION(0, 146),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO135"),
		MTK_FUNCTION(1, "GBE_TXD1"),
		MTK_FUNCTION(2, "SPLIN_BCK"),
		MTK_FUNCTION(3, "RV33_JTAG_TCK"),
		MTK_FUNCTION(7, "DBG_MON_B10")
	),

	MTK_PIN(
		136, "GPIO136",
		MTK_EINT_FUNCTION(0, 147),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO136"),
		MTK_FUNCTION(1, "GBE_TXD0"),
		MTK_FUNCTION(2, "SPLIN_D0"),
		MTK_FUNCTION(3, "RV33_JTAG_TDI"),
		MTK_FUNCTION(7, "DBG_MON_B11")
	),

	MTK_PIN(
		137, "GPIO137",
		MTK_EINT_FUNCTION(0, 148),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO137"),
		MTK_FUNCTION(1, "GBE_TXC"),
		MTK_FUNCTION(2, "SPLIN_D1"),
		MTK_FUNCTION(3, "RV33_JTAG_TRSTN"),
		MTK_FUNCTION(7, "DBG_MON_B12")
	),

	MTK_PIN(
		138, "GPIO138",
		MTK_EINT_FUNCTION(0, 149),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO138"),
		MTK_FUNCTION(1, "GBE_TXEN"),
		MTK_FUNCTION(2, "SPLIN_D2"),
		MTK_FUNCTION(7, "DBG_MON_B13")
	),

	MTK_PIN(
		139, "GPIO139",
		MTK_EINT_FUNCTION(0, 150),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO139"),
		MTK_FUNCTION(1, "GBE_RXD3"),
		MTK_FUNCTION(2, "SPLIN_D3"),
		MTK_FUNCTION(7, "DBG_MON_B14")
	),

	MTK_PIN(
		140, "GPIO140",
		MTK_EINT_FUNCTION(0, 151),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO140"),
		MTK_FUNCTION(1, "GBE_RXD2"),
		MTK_FUNCTION(2, "DMIC_CLK0"),
		MTK_FUNCTION(3, "TDMIN_BCK"),
		MTK_FUNCTION(7, "DBG_MON_B15")
	),

	MTK_PIN(
		141, "GPIO141",
		MTK_EINT_FUNCTION(0, 152),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO141"),
		MTK_FUNCTION(1, "GBE_RXD1"),
		MTK_FUNCTION(2, "DMIC_CLK1"),
		MTK_FUNCTION(3, "TDMIN_DI"),
		MTK_FUNCTION(7, "DBG_MON_B16")
	),

	MTK_PIN(
		142, "GPIO142",
		MTK_EINT_FUNCTION(0, 153),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO142"),
		MTK_FUNCTION(1, "GBE_RXD0"),
		MTK_FUNCTION(2, "DMIC_DAT0"),
		MTK_FUNCTION(3, "TDMIN_LRCK"),
		MTK_FUNCTION(7, "DBG_MON_B17")
	),

	MTK_PIN(
		143, "GPIO143",
		MTK_EINT_FUNCTION(0, 154),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO143"),
		MTK_FUNCTION(1, "GBE_RXDV"),
		MTK_FUNCTION(2, "DMIC_DAT1"),
		MTK_FUNCTION(3, "TDMIN_MCLK"),
		MTK_FUNCTION(7, "DBG_MON_B18")
	),

	MTK_PIN(
		144, "GPIO144",
		MTK_EINT_FUNCTION(0, 155),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO144"),
		MTK_FUNCTION(1, "GBE_RXER"),
		MTK_FUNCTION(2, "DMIC_DAT2"),
		MTK_FUNCTION(7, "DBG_MON_B19")
	),

	MTK_PIN(
		145, "GPIO145",
		MTK_EINT_FUNCTION(0, 156),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO145"),
		MTK_FUNCTION(1, "GBE_RXC"),
		MTK_FUNCTION(2, "DMIC_DAT3"),
		MTK_FUNCTION(7, "DBG_MON_B20")
	),

	MTK_PIN(
		146, "GPIO146",
		MTK_EINT_FUNCTION(0, 157),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO146"),
		MTK_FUNCTION(1, "GBE_MDC"),
		MTK_FUNCTION(7, "DBG_MON_B21")
	),

	MTK_PIN(
		147, "GPIO147",
		MTK_EINT_FUNCTION(0, 158),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO147"),
		MTK_FUNCTION(1, "GBE_MDIO"),
		MTK_FUNCTION(7, "DBG_MON_B22")
	),

	MTK_PIN(
		148, "GPIO148",
		MTK_EINT_FUNCTION(0, 159),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO148"),
		MTK_FUNCTION(1, "GBE_TXER"),
		MTK_FUNCTION(7, "DBG_MON_B23")
	),

	MTK_PIN(
		149, "GPIO149",
		MTK_EINT_FUNCTION(0, 160),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO149"),
		MTK_FUNCTION(1, "GBE_INTR"),
		MTK_FUNCTION(2, "GBE_CRS"),
		MTK_FUNCTION(7, "DBG_MON_B24")
	),

	MTK_PIN(
		150, "GPIO150",
		MTK_EINT_FUNCTION(0, 161),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO150"),
		MTK_FUNCTION(1, "GBE_COL"),
		MTK_FUNCTION(7, "DBG_MON_B25")
	),

	MTK_PIN(
		151, "GPIO151",
		MTK_EINT_FUNCTION(0, 162),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO151"),
		MTK_FUNCTION(1, "MSDC1_CLK"),
		MTK_FUNCTION(2, "UDI_TCK"),
		MTK_FUNCTION(3, "NOR_SPI_IO0"),
		MTK_FUNCTION(4, "SPI_CK"),
		MTK_FUNCTION(5, "MCUPM_JTAG_TCK"),
		MTK_FUNCTION(6, "I2SO1_BCK"),
		MTK_FUNCTION(7, "DBG_MON_B26")
	),

	MTK_PIN(
		152, "GPIO152",
		MTK_EINT_FUNCTION(0, 163),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO152"),
		MTK_FUNCTION(1, "MSDC1_DAT3"),
		MTK_FUNCTION(2, "PWM3"),
		MTK_FUNCTION(3, "NOR_SPI_CK"),
		MTK_FUNCTION(4, "SPI_IO3"),
		MTK_FUNCTION(6, "I2SO1_LRCK"),
		MTK_FUNCTION(7, "DBG_MON_B27")
	),

	MTK_PIN(
		153, "GPIO153",
		MTK_EINT_FUNCTION(0, 164),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO153"),
		MTK_FUNCTION(1, "MSDC1_DAT1"),
		MTK_FUNCTION(2, "UDI_TDO"),
		MTK_FUNCTION(3, "NOR_SPI_CS"),
		MTK_FUNCTION(4, "SPI_IO1"),
		MTK_FUNCTION(5, "MCUPM_JTAG_TDO"),
		MTK_FUNCTION(6, "I2SO1_MCK"),
		MTK_FUNCTION(7, "DBG_MON_B28")
	),

	MTK_PIN(
		154, "GPIO154",
		MTK_EINT_FUNCTION(0, 165),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO154"),
		MTK_FUNCTION(1, "MSDC1_DAT2"),
		MTK_FUNCTION(2, "UDI_NTRST"),
		MTK_FUNCTION(3, "NOR_SPI_IO1"),
		MTK_FUNCTION(4, "SPI_IO2"),
		MTK_FUNCTION(5, "MCUPM_JTAG_TRSTN"),
		MTK_FUNCTION(6, "I2SO1_DATA0"),
		MTK_FUNCTION(7, "DBG_MON_B29")
	),

	MTK_PIN(
		155, "GPIO155",
		MTK_EINT_FUNCTION(0, 166),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO155"),
		MTK_FUNCTION(1, "MSDC1_DAT0"),
		MTK_FUNCTION(2, "UDI_TDI"),
		MTK_FUNCTION(3, "NOR_SPI_IO2"),
		MTK_FUNCTION(4, "SPI_IO0"),
		MTK_FUNCTION(5, "MCUPM_JTAG_TDI"),
		MTK_FUNCTION(6, "I2SO1_DATA1"),
		MTK_FUNCTION(7, "DBG_MON_B30")
	),

	MTK_PIN(
		156, "GPIO156",
		MTK_EINT_FUNCTION(0, 167),
		DRV_GRP4,
		MTK_FUNCTION(0, "GPIO156"),
		MTK_FUNCTION(1, "MSDC1_CMD"),
		MTK_FUNCTION(2, "UDI_TMS"),
		MTK_FUNCTION(3, "NOR_SPI_IO3"),
		MTK_FUNCTION(4, "SPI_CS"),
		MTK_FUNCTION(5, "MCUPM_JTAG_TMS"),
		MTK_FUNCTION(6, "I2SO1_DATA2"),
		MTK_FUNCTION(7, "DBG_MON_B31")
	),

	MTK_PIN(
		157, "USB_GPIO_DP_P0",
		MTK_EINT_FUNCTION(0, 171),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		158, "USB_GPIO_DM_P0",
		MTK_EINT_FUNCTION(0, 172),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		159, "USB_GPIO_DP_P1",
		MTK_EINT_FUNCTION(0, 173),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		160, "USB_GPIO_DM_P1",
		MTK_EINT_FUNCTION(0, 174),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		161, "USB_GPIO_DP_P2",
		MTK_EINT_FUNCTION(0, 175),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		162, "USB_GPIO_DM_P2",
		MTK_EINT_FUNCTION(0, 176),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		163, "SSUSB_EINT_OUT0",
		MTK_EINT_FUNCTION(0, 223),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		164, "SSUSB_EINT_OUT1",
		MTK_EINT_FUNCTION(0, 224),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		165, "SSUSB_EINT_OUT2",
		MTK_EINT_FUNCTION(0, 225),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		166, "SSUSB_EINT_OUT3",
		MTK_EINT_FUNCTION(0, 226),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		167, "SSUSB_EINT_OUT4",
		MTK_EINT_FUNCTION(0, 227),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		168, "SSUSB_EINT_OUT5",
		MTK_EINT_FUNCTION(0, 228),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		169, "SSUSB_EINT_OUT6",
		MTK_EINT_FUNCTION(0, 229),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	),

	MTK_PIN(
		170, "SSUSB_SPM_INT",
		MTK_EINT_FUNCTION(0, 230),
		DRV_FIXED,
		MTK_FUNCTION(0, NULL)
	)
};

#endif /* __PINCTRL__MTK_MT8696_H */
