// SPDX-License-Identifier: GPL-2.0
//
// Copyright (c) 2021 MediaTek Inc.
// Author: Chun-Jie Chen <chun-jie.chen@mediatek.com>

#include <linux/clk.h>
#include <linux/clk-provider.h>
#include <linux/delay.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/seq_file.h>
#include <linux/module.h>
#include <linux/platform_device.h>

#include <dt-bindings/power/mt8188-power.h>

#include "clkdbg.h"
#include "clkchk.h"
#include "clk-fmeter.h"

static void __iomem *scpsys_base, *topck_base;

/*
 * clkdbg dump_state
 */

#define FMCLK(_t, _i, _n) { .type = _t, .id = _i, .name = _n }

static const struct fmeter_clk fclks[] = {
	FMCLK(CKGEN, 0, "hd_faxi_ck"),
	FMCLK(CKGEN, 1, "hg_fspm_ck"),
	FMCLK(CKGEN, 2, "hf_fscp_ck"),
	FMCLK(CKGEN, 3, "hd_fbus_aximem_ck"),
	FMCLK(CKGEN, 4, "hf_fvpp_ck"),
	FMCLK(CKGEN, 5, "hf_fethdr_ck"),
	FMCLK(CKGEN, 6, "hf_fipe_ck"),
	FMCLK(CKGEN, 7, "hf_fcam_ck"),
	FMCLK(CKGEN, 8, "hf_fccu_ck"),
	FMCLK(CKGEN, 9, "hf_fccu_ahb_ck"),
	FMCLK(CKGEN, 10, "hf_fimg_ck"),
	FMCLK(CKGEN, 11, "hf_fcamtm_ck"),
	FMCLK(CKGEN, 12, "hf_fdsp_ck"),
	FMCLK(CKGEN, 13, "hf_fdsp1_ck"),
	FMCLK(CKGEN, 14, "hf_fdsp2_ck"),
	FMCLK(CKGEN, 15, "hf_fdsp3_ck"),
	FMCLK(CKGEN, 16, "hf_fdsp4_ck"),
	FMCLK(CKGEN, 17, "hf_fdsp5_ck"),
	FMCLK(CKGEN, 18, "hf_fdsp6_ck"),
	FMCLK(CKGEN, 19, "hf_fdsp7_ck"),
	FMCLK(CKGEN, 20, "hf_fmfg_core_tmp_ck"),
	FMCLK(CKGEN, 21, "f_fcamtg_ck"),
	FMCLK(CKGEN, 22, "f_fcamtg2_ck"),
	FMCLK(CKGEN, 23, "f_fcamtg3_ck"),
	FMCLK(CKGEN, 24, "f_fuart_ck"),
	FMCLK(CKGEN, 25, "hf_fspi_ck"),
	FMCLK(CKGEN, 26, "hf_fmsdc50_0_hclk_ck"),
	FMCLK(CKGEN, 27, "hf_fmsdc50_0_ck"),
	FMCLK(CKGEN, 28, "hf_fmsdc30_1_ck"),
	FMCLK(CKGEN, 29, "hf_fmsdc30_2_ck"),
	FMCLK(CKGEN, 30, "hf_fintdir_ck"),
	FMCLK(CKGEN, 31, "hf_faud_intbus_ck"),
	FMCLK(CKGEN, 32, "hf_faudio_h_ck"),
	FMCLK(CKGEN, 33, "f_fpwrap_ulposc_ck"),
	FMCLK(CKGEN, 34, "hf_fatb_ck"),
	FMCLK(CKGEN, 35, "hf_fsspm_ck"),
	FMCLK(CKGEN, 36, "hf_fdp_ck"),
	FMCLK(CKGEN, 37, "hf_fedp_ck"),
	FMCLK(CKGEN, 38, "hf_fdpi_ck"),
	FMCLK(CKGEN, 39, "f_fdisp_pwm0_ck"),
	FMCLK(CKGEN, 40, "f_fdisp_pwm1_ck"),
	FMCLK(CKGEN, 41, "f_fusb_top_ck"),
	FMCLK(CKGEN, 42, "f_fssusb_xhci_ck"),
	FMCLK(CKGEN, 43, "f_fusb_top_2p_ck"),
	FMCLK(CKGEN, 44, "f_fssusb_xhci_2p_ck"),
	FMCLK(CKGEN, 45, "f_fusb_top_3p_ck"),
	FMCLK(CKGEN, 46, "f_fssusb_xhci_3p_ck"),
	FMCLK(CKGEN, 47, "f_fi2c_ck"),
	FMCLK(CKGEN, 48, "f_fseninf_ck"),
	FMCLK(CKGEN, 49, "f_fseninf1_ck"),
	FMCLK(CKGEN, 50, "hf_gcpu_ck"),
	FMCLK(CKGEN, 51, "hf_fvenc_ck"),
	FMCLK(CKGEN, 52, "hf_fvdec_ck"),
	FMCLK(CKGEN, 53, "hf_fpwm_ck"),
	FMCLK(CKGEN, 54, "hg_mcupm_ck"),
	FMCLK(CKGEN, 55, "hf_fspmi_p_mst_ck"),
	FMCLK(CKGEN, 56, "hf_fspmi_m_mst_ck"),
	FMCLK(CKGEN, 57, "hg_fdvfsrc_ck"),
	FMCLK(CKGEN, 58, "hf_ftl_ck"),
	FMCLK(CKGEN, 59, "hf_faes_msdcfde_ck"),
	FMCLK(CKGEN, 60, "hf_dsi_occ_ck"),
	FMCLK(CKGEN, 61, "hf_fwpe_vpp_ck"),
	FMCLK(CKGEN, 62, "hf_fhdcp_ck"),
	FMCLK(CKGEN, 63, "hf_fhdcp_24m_ck"),
	FMCLK(CKGEN, 64, "hf_fhdmi_apb_ck"),
	FMCLK(CKGEN, 65, "hf_fsnps_eth_250m_ck"),
	FMCLK(CKGEN, 66, "hf_fsnps_eth_62p4m_ptp_ck"),
	FMCLK(CKGEN, 67, "hf_fsnps_eth_50m_rmii_ck"),
	FMCLK(CKGEN, 68, "hf_fadsp_ck"),
	FMCLK(CKGEN, 69, "hf_faudio_local_bus_ck"),
	FMCLK(CKGEN, 70, "hf_fasm_h_ck"),
	FMCLK(CKGEN, 71, "hf_fasm_l_ck"),
	FMCLK(CKGEN, 72, "hf_fapll1_ck"),
	FMCLK(CKGEN, 73, "hf_fapll2_ck"),
	FMCLK(CKGEN, 74, "hf_fapll3_ck"),
	FMCLK(CKGEN, 75, "hf_fapll4_ck"),
	FMCLK(CKGEN, 76, "hf_fapll5_ck"),
	FMCLK(CKGEN, 77, "hf_fi2so1_mck"),
	FMCLK(CKGEN, 78, "hf_fi2so2_mck"),
	FMCLK(CKGEN, 79, "hf_fi2si1_mck"),
	FMCLK(CKGEN, 80, "hf_fi2si2_mck"),
	FMCLK(CKGEN, 81, "hf_fdptx_mck"),
	FMCLK(CKGEN, 82, "hf_aud_iec_clk"),
	FMCLK(CKGEN, 83, "hf_a1sys_hp_ck"),
	FMCLK(CKGEN, 84, "hf_a2sys_hf_ck"),
	FMCLK(CKGEN, 85, "hf_a3sys_hf_ck"),
	FMCLK(CKGEN, 86, "hf_a4sys_hf_ck"),
	FMCLK(CKGEN, 87, "hf_ecc_ck"),
	FMCLK(CKGEN, 88, "hf_fspinor_ck"),
	FMCLK(CKGEN, 89, "f_ulposc_ck"),
	FMCLK(CKGEN, 90, "hf_fsrck_ck"),
	FMCLK(CKGEN, 91, "src_occ_50m_clk"),
	FMCLK(CKGEN, 92, "src_occ_78m_clk"),
	FMCLK(CKGEN, 93, "src_occ_125m_clk"),
	FMCLK(CKGEN, 94, "src_occ_250m_clk"),
	FMCLK(CKGEN, 95, "src_occ_500m_clk"),
	FMCLK(CKGEN, 96, "src_occ_240m_clk"),
	FMCLK(CKGEN, 97, "src_occ_810m_clk"),
	FMCLK(CKGEN, 98, "src_occ_202m_clk"),
	FMCLK(CKGEN, 99, "src_occ_100m_clk"),
	FMCLK(CKGEN, 100, "src_occ_208m_clk"),
	FMCLK(CKGEN, 101, "src_occ_202m_1_clk"),
	FMCLK(CKGEN, 102, "src_occ_594m_clk"),
	FMCLK(CKGEN, 103, "src_occ_gcpu_div2_ck"),
	FMCLK(CKGEN, 104, "f_rsvd1_ck"),
	FMCLK(CKGEN, 105, "f_rsvd2_ck"),
	FMCLK(CKGEN, 106, "f_rsvd3_ck"),
	FMCLK(ABIST, 1, "ad_armpll_ll_ck"),
	FMCLK(ABIST, 2, "ad_armpll_bl_ck"),
	FMCLK(ABIST, 3, "ad_ccipll_ck"),
	FMCLK(ABIST, 4, "ad_appllgp1_mon_fm_ck"),
	FMCLK(ABIST, 5, "ad_apll1_ck"),
	FMCLK(ABIST, 6, "ad_apll2_ck"),
	FMCLK(ABIST, 7, "ad_apll3_ck"),
	FMCLK(ABIST, 8, "ad_mfgpll_ck"),
	FMCLK(ABIST, 9, "ad_mfgpll_opp_ck"),
	FMCLK(ABIST, 10, "ad_apll4_ck"),
	FMCLK(ABIST, 11, "ad_apll5_ck"),
	FMCLK(ABIST, 12, "ad_adsppll_ck"),
	FMCLK(ABIST, 13, "ad_mpll_ck"),
	FMCLK(ABIST, 14, "ad_ethpll_ck"),
	FMCLK(ABIST, 15, "ad_mainpll_ck"),
	FMCLK(ABIST, 16, "ad_mainpll_div2_ck"),
	FMCLK(ABIST, 17, "ad_mainpll_div3_ck"),
	FMCLK(ABIST, 18, "ad_mainpll_div4_ck"),
	FMCLK(ABIST, 19, "ad_mainpll_div5_ck"),
	FMCLK(ABIST, 20, "ad_mainpll_div6_ck"),
	FMCLK(ABIST, 21, "ad_mainpll_div7_ck"),
	FMCLK(ABIST, 22, "ad_mainpll_div9_ck"),
	FMCLK(ABIST, 23, "ad_univpll_ck"),
	FMCLK(ABIST, 24, "ad_univpll_div2_ck"),
	FMCLK(ABIST, 25, "ad_univpll_div3_ck"),
	FMCLK(ABIST, 26, "ad_univpll_div4_ck"),
	FMCLK(ABIST, 27, "ad_univpll_div5_ck"),
	FMCLK(ABIST, 28, "ad_univpll_div6_ck"),
	FMCLK(ABIST, 29, "ad_univpll_div7_ck"),
	FMCLK(ABIST, 30, "ad_msdcpll_ck"),
	FMCLK(ABIST, 31, "ad_tvdpll1_ck"),
	FMCLK(ABIST, 32, "ad_tvdpll2_ck"),
	FMCLK(ABIST, 33, "ad_mmpll_ck"),
	FMCLK(ABIST, 34, "ad_mmpll_d3_ck"),
	FMCLK(ABIST, 35, "ad_mmpll_d4_ck"),
	FMCLK(ABIST, 36, "ad_mmpll_d5_ck"),
	FMCLK(ABIST, 37, "ad_mmpll_d6_ck"),
	FMCLK(ABIST, 38, "ad_mmpll_d7_ck"),
	FMCLK(ABIST, 39, "ad_mmpll_d9_ck"),
	FMCLK(ABIST, 40, "ad_imgpll_ck"),
	FMCLK(ABIST, 41, "ad_usb20_192m_ck"),
	FMCLK(ABIST, 42, "ad_ulposc_ck"),
	FMCLK(ABIST, 43, "ad_osc_sync_ck"),
	FMCLK(ABIST, 44, "ad_ulposc2_ck"),
	FMCLK(ABIST, 45, "ad_osc_sync_ck_2"),
	FMCLK(ABIST, 46, "ad_clksq_fs26m_ck"),
	FMCLK(ABIST, 47, "_fixed_0"),
	FMCLK(ABIST, 48, "_fixed_0"),
	FMCLK(ABIST, 49, "dsi0_ad_dsi_ckg_dsiclk_anaout"),
	FMCLK(ABIST, 50, "dsi0_ad_dsi_test_ck_anaout"),
	FMCLK(ABIST, 51, "dsi1_ad_dsi_ckg_dsiclk_anaout"),
	FMCLK(ABIST, 52, "dsi1_ad_dsi_test_ck_anaout"),
	FMCLK(ABIST, 53, "ada_lvts_to_pllgp_mon_ck_l1"),
	FMCLK(ABIST, 54, "ada_lvts_to_pllgp_mon_ck_l2"),
	FMCLK(ABIST, 55, "ada_lvts_to_pllgp_mon_ck_l3"),
	FMCLK(ABIST, 56, "ada_lvts_to_pllgp_mon_ck_l4"),
	FMCLK(ABIST, 57, "ada_lvts_to_pllgp_mon_ck_l5"),
	FMCLK(ABIST, 58, "ada_lvts_to_pllgp_mon_ck_l6"),
	FMCLK(ABIST, 59, "ad_csi0a_cdphy_delaycal_ck"),
	FMCLK(ABIST, 60, "ad_csi0b_cdphy_delaycal_ck"),
	FMCLK(ABIST, 61, "ad_csi0c_cdphy_delaycal_ck"),
	FMCLK(ABIST, 62, "ad_csi0d_cdphy_delaycal_ck"),
	FMCLK(ABIST, 63, "spdifin_iec_ck"),
	FMCLK(ABIST, 64, "other_splin_bck_i"),
	FMCLK(ABIST, 65, "other_splin_mck_i"),
	FMCLK(ABIST, 66, "apll_i2sin_mck_i"),
	FMCLK(ABIST, 67, "apll_i2sin_bck_i"),
	FMCLK(ABIST, 68, "u2a_rx_sof_p0"),
	FMCLK(ABIST, 69, "u2a_tx_sof_p0"),
	FMCLK(ABIST, 70, "u2a_rx_sof_p1"),
	FMCLK(ABIST, 71, "u2a_tx_sof_p1"),
	FMCLK(ABIST, 72, "u2a_rx_sof_p2"),
	FMCLK(ABIST, 73, "u2a_tx_sof_p2"),
	FMCLK(ABIST, 74, "other_tdmin_mck_i"),
	FMCLK(ABIST, 75, "apll_i2so2_bck_i"),
	FMCLK(ABIST, 76, "ad_hdmitx21pll_monref_ck"),
	FMCLK(ABIST, 77, "ad_hdmitx21pll_monfbk_ck"),
	FMCLK(ABIST, 78, "ad_hdmitx21_clkdig_1"),
	FMCLK(ABIST, 79, "ad_hdmitx21_clkdig_1_cts"),
	FMCLK(ABIST, 80, "ad_hdmitxpll_pixel_ck"),
	FMCLK(ABIST, 81, "mcusys_arm_clk_out_all"),
	FMCLK(ABIST, 82, "ad_rphypll_div4_ck_ch01"),
	FMCLK(ABIST, 83, "ad_rclrpll_div4_ck_ch01"),
	FMCLK(ABIST, 84, "fmem_ck_bfe_dcm_ch0"),
	FMCLK(ABIST, 85, "fmem_ck_aft_dcm_ch0"),
	FMCLK(ABIST, 86, "ad_rphypll_div4_ck_ch23"),
	FMCLK(ABIST, 87, "ad_rclrpll_div4_ck_ch23"),
	FMCLK(ABIST, 88, "fmem_ck_bfe_dcm_ch2"),
	FMCLK(ABIST, 89, "fmem_ck_aft_dcm_ch2"),
	FMCLK(ABIST, 90, "ad_usb20_clk480m_p0"),
	FMCLK(ABIST, 91, "ad_usb20_clk480m_p1"),
	FMCLK(ABIST, 92, "ad_usb20_clk480m_p2"),
	{}
};

static const struct fmeter_clk *get_all_fmeter_clks(void)
{
	return fclks;
}

#define CLK_MISC_CFG_0	(topck_base + 0x22C)
#define CLK_DBG_CFG	(topck_base + 0x20C)
#define CLK26CALI_0	(topck_base + 0x218)
#define CLK26CALI_1	(topck_base + 0x21C)

static unsigned int get_ckgen_freq(unsigned int ID)
{
	int output = 0, i = 0;
	unsigned int temp, clk26cali_0, clk_dbg_cfg, clk_misc_cfg_0, clk26cali_1;
	bool timeout = false;

	clk_dbg_cfg = clk_readl(CLK_DBG_CFG);
	clk_writel(CLK_DBG_CFG, (clk_dbg_cfg & 0xFE00FFFC) | (ID << 16) | 0x1 | (0x1 << 24));

	clk_misc_cfg_0 = clk_readl(CLK_MISC_CFG_0);
	clk_writel(CLK_MISC_CFG_0, (clk_misc_cfg_0 & 0x00FFFFFF)); /* divider = 0*/
	clk26cali_0 = clk_readl(CLK26CALI_0);
	clk26cali_1 = clk_readl(CLK26CALI_1);
	clk_writel(CLK26CALI_0, 0x80);
	clk_writel(CLK26CALI_0, 0x90);

	/* wait frequency meter finish */
	while (clk_readl(CLK26CALI_0) & 0x10) {
		udelay(10);
		i++;
		if (i > 10000) {
			timeout = true;
			pr_info("ckgen meter[%d], timeout\n", ID);
			break;
		}
	}

	if (!timeout) {
		temp = clk_readl(CLK26CALI_1) & 0xFFFF;
		output = (temp * 26000) / 1024; /* KHz */
	} else {
		output = 0;
	}

	clk_writel(CLK_DBG_CFG, clk_dbg_cfg);
	clk_writel(CLK_MISC_CFG_0, clk_misc_cfg_0);
	clk_writel(CLK26CALI_0, clk26cali_0);
	clk_writel(CLK26CALI_1, clk26cali_1);

	/* pr_info("ckgen meter[%d] = %d KHz\n", ID, output); */
	return output;
}

static unsigned int get_abist_freq(unsigned int ID)
{
	int output = 0, i = 0;
	unsigned int temp, clk26cali_0, clk_dbg_cfg, clk_misc_cfg_0, clk26cali_1;
	bool timeout = false;

	clk_dbg_cfg = clk_readl(CLK_DBG_CFG);
	clk_writel(CLK_DBG_CFG, (clk_dbg_cfg & 0xFEFF80FC) | (ID << 8));
	clk_misc_cfg_0 = clk_readl(CLK_MISC_CFG_0);
	clk_writel(CLK_MISC_CFG_0, (clk_misc_cfg_0 & 0x00FFFFFF) | (3 << 24)); /* divider = 4 */
	clk26cali_0 = clk_readl(CLK26CALI_0);
	clk26cali_1 = clk_readl(CLK26CALI_1);
	clk_writel(CLK26CALI_0, 0x80);
	clk_writel(CLK26CALI_0, 0x90);

	/* wait frequency meter finish */
	while (clk_readl(CLK26CALI_0) & 0x10) {
		udelay(10);
		i++;
		if (i > 10000) {
			timeout = true;
			pr_info("abist meter[%d], timeout\n", ID);
			break;
		}
	}

	if (!timeout) {
		temp = clk_readl(CLK26CALI_1) & 0xFFFF;
		output = (temp * 26000) / 1024; /* KHz */
	} else {
		output = 0;
	}

	clk_writel(CLK_DBG_CFG, clk_dbg_cfg);
	clk_writel(CLK_MISC_CFG_0, clk_misc_cfg_0);
	clk_writel(CLK26CALI_0, clk26cali_0);
	clk_writel(CLK26CALI_1, clk26cali_1);

	/* pr_info("abist meter[%d] = %d KHz\n", ID, output * 4); */
	return output * 4;
}

static u32 fmeter_freq_op(const struct fmeter_clk *fclk)
{
	if (fclk->type == ABIST)
		return get_abist_freq(fclk->id);
	else if (fclk->type == CKGEN)
		return get_ckgen_freq(fclk->id);
	return 0;
}


static const char * const clk_names[] = {
	"ethpll",
	"msdcpll",
	"tvdpll1",
	"tvdpll2",
	"mmpll",
	"mainpll",
	"imgpll",
	"univpll",
	"adsppll",
	"apll1",
	"apll2",
	"apll3",
	"apll4",
	"apll5",
	"mfgpll",
	"pll_ssusb26m_en",
	"cfgreg_clock_vpp0",
	"cfgreg_clock_vpp1",
	"cfgreg_clock_vdo0",
	"cfgreg_clock_vdo1",
	"cfgreg_clock_isp_axi_gals",
	"cfgreg_f26m_vpp0",
	"cfgreg_f26m_vpp1",
	"cfgreg_f26m_vdo0",
	"cfgreg_f26m_vdo1",
	"cfgreg_aud_f26m_aud",
	"cfgreg_unipll_ses",
	"cfgreg_f_pcie_phy_ref",
	"ssusb_ref",
	"ssusb_phy_ref",
	"ssusb_p1_ref",
	"ssusb_phy_p1_ref",
	"ssusb_p2_ref",
	"ssusb_phy_p2_ref",
	"ssusb_p3_ref",
	"ssusb_phy_p3_ref",
	"axi_sel",
	"spm_sel",
	"scp_sel",
	"bus_aximem_sel",
	"vpp_sel",
	"ethdr_sel",
	"ipe_sel",
	"cam_sel",
	"ccu_sel",
	"ccu_ahb_sel",
	"img_sel",
	"camtm_sel",
	"dsp_sel",
	"dsp1_sel",
	"dsp2_sel",
	"dsp3_sel",
	"dsp4_sel",
	"dsp5_sel",
	"dsp6_sel",
	"dsp7_sel",
	"mfg_core_tmp_sel",
	"camtg_sel",
	"camtg2_sel",
	"camtg3_sel",
	"uart_sel",
	"spi_sel",
	"msdc5hclk_sel",
	"msdc50_0_sel",
	"msdc30_1_sel",
	"msdc30_2_sel",
	"intdir_sel",
	"aud_intbus_sel",
	"audio_h_sel",
	"pwrap_ulposc_sel",
	"atb_sel",
	"sspm_sel",
	"dp_sel",
	"edp_sel",
	"dpi_sel",
	"disp_pwm0_sel",
	"disp_pwm1_sel",
	"usb_sel",
	"ssusb_xhci_sel",
	"usb_2p_sel",
	"ssusb_xhci_2p_sel",
	"usb_3p_sel",
	"ssusb_xhci_3p_sel",
	"i2c_sel",
	"seninf_sel",
	"seninf1_sel",
	"gcpu_sel",
	"venc_sel",
	"vdec_sel",
	"pwm_sel",
	"mcupm_sel",
	"spmi_p_mst_sel",
	"spmi_m_mst_sel",
	"dvfsrc_sel",
	"tl_sel",
	"aes_msdcfde_sel",
	"dsi_occ_sel",
	"wpe_vpp_sel",
	"hdcp_sel",
	"hdcp_24m_sel",
	"hdmi_apb_sel",
	"snps_eth_250m_sel",
	"snps_eth_62p4m_ptp_sel",
	"snps_eth_50m_rmii_sel",
	"adsp_sel",
	"audio_local_bus_sel",
	"asm_h_sel",
	"asm_l_sel",
	"apll1_sel",
	"apll2_sel",
	"apll3_sel",
	"apll4_sel",
	"apll5_sel",
	"i2so1_sel",
	"i2so2_sel",
	"i2si1_sel",
	"i2si2_sel",
	"dptx_sel",
	"aud_iec_sel",
	"a1sys_hp_sel",
	"a2sys_sel",
	"a3sys_sel",
	"a4sys_sel",
	"ecc_sel",
	"spinor_sel",
	"ulposc_sel",
	"srck_sel",
	"mfg_fast_ref_sel",
	"mfgpll_ck",
	"mainpll_ck",
	"mainpll_d3",
	"mainpll_d4",
	"mainpll_d4_d2",
	"mainpll_d4_d4",
	"mainpll_d4_d8",
	"mainpll_d5",
	"mainpll_d5_d2",
	"mainpll_d5_d4",
	"mainpll_d5_d8",
	"mainpll_d6",
	"mainpll_d6_d2",
	"mainpll_d6_d4",
	"mainpll_d6_d8",
	"mainpll_d7",
	"mainpll_d7_d2",
	"mainpll_d7_d4",
	"mainpll_d7_d8",
	"mainpll_d9",
	"univpll_ck",
	"univpll_d3",
	"univpll_d4",
	"univpll_d4_d2",
	"univpll_d4_d4",
	"univpll_d4_d8",
	"univpll_d5",
	"univpll_d5_d2",
	"univpll_d5_d4",
	"univpll_d5_d8",
	"univpll_d6",
	"univpll_d6_d2",
	"univpll_d6_d4",
	"univpll_d6_d8",
	"univpll_d7",
	"univpll_192m",
	"univpll_192m_d4",
	"univpll_192m_d8",
	"univpll_192m_d10",
	"univpll_192m_d16",
	"univpll_192m_d32",
	"imgpll_ck",
	"apll1_ck",
	"apll1_d3",
	"apll1_d4",
	"apll2_ck",
	"apll2_d3",
	"apll2_d4",
	"apll3_ck",
	"apll3_d4",
	"apll4_ck",
	"apll4_d4",
	"apll5_ck",
	"apll5_d4",
	"mmpll_ck",
	"mmpll_d4",
	"mmpll_d4_d2",
	"mmpll_d5",
	"mmpll_d5_d2",
	"mmpll_d5_d4",
	"mmpll_d6",
	"mmpll_d6_d2",
	"mmpll_d7",
	"mmpll_d9",
	"tvdpll1_ck",
	"tvdpll1_d2",
	"tvdpll1_d4",
	"tvdpll1_d8",
	"tvdpll1_d16",
	"tvdpll2_ck",
	"tvdpll2_d2",
	"tvdpll2_d4",
	"tvdpll2_d8",
	"tvdpll2_d16",
	"msdcpll_ck",
	"msdcpll_d2",
	"msdcpll_d16",
	"ethpll_ck",
	"ethpll_d2",
	"ethpll_d4",
	"ethpll_d8",
	"ethpll_d10",
	"adsppll_ck",
	"adsppll_d2",
	"adsppll_d4",
	"adsppll_d8",
	"ulposc_ck",
	"ulposc_d2",
	"ulposc_d4",
	"ulposc_d8",
	"ulposc_d7",
	"ulposc_d10",
	"ulposc_d16",
	"mphone_slave_bck",
	"pad_fpc_ck",
	"hd_466m_fmem_ck",
	"apll12_div0",
	"apll12_div1",
	"apll12_div2",
	"apll12_div3",
	"apll12_div4",
	"apll12_div9",
	"infra_ao_pmic_tmr",
	"infra_ao_pmic_ap",
	"infra_ao_pmic_md",
	"infra_ao_pmic_conn",
	"infra_ao_sej",
	"infra_ao_apxgpt",
	"infra_ao_gce",
	"infra_ao_gce2",
	"infra_ao_therm",
	"infra_ao_pwm_hclk",
	"infra_ao_pwm1",
	"infra_ao_pwm2",
	"infra_ao_pwm3",
	"infra_ao_pwm4",
	"infra_ao_pwm",
	"infra_ao_uart0",
	"infra_ao_uart1",
	"infra_ao_uart2",
	"infra_ao_uart3",
	"infra_ao_uart4",
	"infra_ao_gce_26m",
	"infra_ao_dma",
	"infra_ao_uart5",
	"infra_ao_hdmi_26m",
	"infra_ao_spi0",
	"infra_ao_msdc0",
	"infra_ao_msdc1",
	"infra_ao_msdc2",
	"infra_ao_msdc0_clk",
	"infra_ao_dvfsrc",
	"infra_ao_trng",
	"infra_ao_auxadc",
	"infra_ao_cpum",
	"infra_ao_hdmi_32k",
	"infra_ao_cec_66m_hclk",
	"infra_ao_pcie_tl_26m",
	"infra_ao_msdc1_clk",
	"infra_ao_cec_66m_bclk",
	"infra_ao_pcie_tl_96m",
	"infra_ao_dapc",
	"infra_ao_ecc_66m_hclk",
	"infra_ao_debugsys",
	"infra_ao_audio",
	"infra_ao_pcie_tl_32k",
	"infra_ao_dbg_trace",
	"infra_ao_dramc26",
	"infra_ao_irtx",
	"infra_ao_disp_pwm",
	"infra_ao_cldmabclk",
	"infra_ao_audio26m",
	"infra_ao_spi1",
	"infra_ao_spi2",
	"infra_ao_spi3",
	"infra_ao_fsspm",
	"infra_ao_sspm_hclk",
	"infra_ao_apdma_bclk",
	"infra_ao_spi4",
	"infra_ao_spi5",
	"infra_ao_cq_dma",
	"infra_ao_msdc0sf",
	"infra_ao_msdc1sf",
	"infra_ao_msdc2sf",
	"infra_ao_i2s_dma",
	"infra_ao_ap_msdc0",
	"infra_ao_md_msdc0",
	"infra_ao_msdc30_2",
	"infra_ao_gcpu",
	"infra_ao_pcie_peri_26m",
	"infra_ao_gcpu_66m_bclk",
	"infra_ao_gcpu_133m_bclk",
	"infra_ao_disp_pwm1",
	"infra_ao_fbist2fpc",
	"infra_ao_dapc_sync",
	"infra_ao_pcie_p1_peri_26m",
	"infra_ao_133m_mclk",
	"infra_ao_66m_mclk",
	"infra_ao_aes_msdcfde_0p",
	"audio_src_asrc0",
	"audio_src_asrc1",
	"audio_src_asrc2",
	"audio_src_asrc3",
	"aud_afe",
	"aud_lrck_cnt",
	"aud_spdifin_tuner_apll_ck",
	"aud_spdifin_tuner_dbg_ck",
	"aud_ul_tml",
	"aud_apll1_tuner_ck",
	"aud_apll2_tuner_ck",
	"aud_top0_spdf_ck",
	"aud_apll_ck",
	"aud_apll2_ck",
	"aud_dac",
	"aud_dac_predis",
	"aud_tml",
	"aud_adc",
	"aud_dac_hires",
	"aud_a1sys_hp_ck",
	"aud_afe_dmic1_26m_ul_hop_bclk_ck",
	"aud_afe_dmic2_26m_ul_hop_bclk_ck",
	"aud_afe_dmic3_26m_ul_hop_bclk_ck",
	"aud_afe_dmic4_26m_ul_hop_bclk_ck",
	"aud_afe_26m_dmic_tm_ck",
	"aud_ul_tml_hires",
	"aud_adc_hires",
	"aud_adda6_adc",
	"aud_adda6_adc_hires",
	"aud_dmic1_adc_hires",
	"aud_dmic2_adc_hires",
	"aud_dmic3_adc_hires",
	"aud_dmic4_adc_hires",
	"aud_top2_spdf_ck",
	"aud_linein_tuner_ck",
	"aud_earc_tuner_ck",
	"aud_i2sin",
	"aud_tdm_in",
	"aud_i2s_out",
	"aud_tdm_out",
	"aud_hdmi_out",
	"aud_asrc11",
	"aud_asrc12",
	"aud_multi_in",
	"aud_intdir",
	"aud_a1sys",
	"aud_a2sys",
	"aud_pcmif",
	"aud_a3sys",
	"aud_a4sys",
	"aud_memif_ul1",
	"aud_memif_ul2",
	"aud_memif_ul3",
	"aud_memif_ul4",
	"aud_memif_ul5",
	"aud_memif_ul6",
	"aud_memif_ul8",
	"aud_memif_ul9",
	"aud_memif_ul10",
	"aud_memif_dl2",
	"aud_memif_dl3",
	"aud_memif_dl6",
	"aud_memif_dl7",
	"aud_memif_dl8",
	"aud_memif_dl10",
	"aud_memif_dl11",
	"aud_gasrc0",
	"aud_gasrc1",
	"aud_gasrc2",
	"aud_gasrc3",
	"aud_gasrc4",
	"aud_gasrc5",
	"aud_gasrc6",
	"aud_gasrc7",
	"aud_gasrc8",
	"aud_gasrc9",
	"aud_gasrc10",
	"aud_gasrc11",
	"peri_ao_ethernet",
	"peri_ao_ethernet_bus",
	"peri_ao_flashif_bus",
	"peri_ao_flashif_26m",
	"peri_ao_flashiflashck",
	"peri_ao_ssusb_2p_bus",
	"peri_ao_ssusb_2p_xhci",
	"peri_ao_ssusb_3p_bus",
	"peri_ao_ssusb_3p_xhci",
	"peri_ao_ssusb_bus",
	"peri_ao_ssusb_xhci",
	"peri_ao_ethernet_mac_clk",
	"peri_ao_pcie_p0_fmem",
	"imp_iic_wrap_c_ap_clock_i2c0",
	"imp_iic_wrap_c_ap_clock_i2c2",
	"imp_iic_wrap_c_ap_clock_i2c3",
	"imp_iic_wrap_w_ap_clock_i2c1",
	"imp_iic_wrap_w_ap_clock_i2c4",
	"imp_iic_wrap_ap_clock_i2c5",
	"imp_iic_wrap_ap_clock_i2c6",
	"mfgcfg_bg3d",
	"vpp0_mdp_fg",
	"vpp0_stitch",
	"vpp0_padding",
	"vpp0_mdp_tcc",
	"vpp0_warp0_async_tx",
	"vpp0_warp1_async_tx",
	"vpp0_mutex",
	"vpp02vpp1_relay",
	"vpp0_vpp12vpp0_async",
	"vpp0_mmsysram_top",
	"vpp0_mdp_aal",
	"vpp0_mdp_rsz",
	"vpp0_smi_common_mmsram",
	"vpp0_gals_vdo0_larb0_mmsram",
	"vpp0_gals_vdo0_larb1_mmsram",
	"vpp0_gals_vencsys_mmsram",
	"vpp0_gals_vencsys_core1_mmsram",
	"vpp0_gals_infra_mmsram",
	"vpp0_gals_camsys_mmsram",
	"vpp0_gals_vpp1_larb5_mmsram",
	"vpp0_gals_vpp1_larb6_mmsram",
	"vpp0_smi_reorder_mmsram",
	"vpp0_smi_iommu",
	"vpp0_gals_imgsys_camsys",
	"vpp0_mdp_rdma",
	"vpp0_mdp_wrot",
	"vpp0_gals_emi0_emi1",
	"vpp0_smi_sub_common_reorder",
	"vpp0_smi_rsi",
	"vpp0_smi_common_larb4",
	"vpp0_gals_vdec_vdec_core1",
	"vpp0_gals_vpp1_wpesys",
	"vpp0_gals_vdo0_vdo1_vencsys_core1",
	"vpp0_fake_eng",
	"vpp0_mdp_hdr",
	"vpp0_mdp_tdshp",
	"vpp0_mdp_color",
	"vpp0_mdp_ovl",
	"vpp0_dsip_rdma",
	"vpp0_disp_wdma",
	"vpp0_mdp_hms",
	"vpp0_warp0_relay",
	"vpp0_warp0_async",
	"vpp0_warp1_relay",
	"vpp0_warp1_async",
	"wpe_wpe_vpp0",
	"wpe_smi_larb7",
	"wpe_wpesys_event_tx",
	"wpe_smi_larb7_p_en",
	"wpe_vpp0_veci",
	"wpe_vpp0_vec2i",
	"wpe_vpp0_vec3i",
	"wpe_vpp0_wpeo",
	"wpe_vpp0_msko",
	"wpe_vpp0_vgen",
	"wpe_vpp0_ext",
	"wpe_vpp0_vfc",
	"wpe_vpp0_cach0_top",
	"wpe_vpp0_cach0_dma",
	"wpe_vpp0_cach1_top",
	"wpe_vpp0_cach1_dma",
	"wpe_vpp0_cach2_top",
	"wpe_vpp0_cach2_dma",
	"wpe_vpp0_cach3_top",
	"wpe_vpp0_cach3_dma",
	"wpe_vpp0_psp",
	"wpe_vpp0_psp2",
	"wpe_vpp0_sync",
	"wpe_vpp0_c24",
	"wpe_vpp0_mdp_crop",
	"wpe_vpp0_isp_crop",
	"wpe_vpp0_top",
	"vpp1_svpp1_mdp_ovl",
	"vpp1_svpp1_mdp_tcc",
	"vpp1_svpp1_mdp_wrot",
	"vpp1_svpp1_vpp_pad",
	"vpp1_svpp2_mdp_wrot",
	"vpp1_svpp2_vpp_pad",
	"vpp1_svpp3_mdp_wrot",
	"vpp1_svpp3_vpp_pad",
	"vpp1_svpp1_mdp_rdma",
	"vpp1_svpp1_mdp_fg",
	"vpp1_svpp2_mdp_rdma",
	"vpp1_svpp2_mdp_fg",
	"vpp1_svpp3_mdp_rdma",
	"vpp1_svpp3_mdp_fg",
	"vpp1_vpp_split",
	"vpp1_svpp2_vdo0_dl_relay",
	"vpp1_svpp1_mdp_rsz",
	"vpp1_svpp1_mdp_tdshp",
	"vpp1_svpp1_mdp_color",
	"vpp1_svpp3_vdo1_dl_relay",
	"vpp1_svpp2_mdp_rsz",
	"vpp1_svpp2_vpp_merge",
	"vpp1_svpp2_mdp_tdshp",
	"vpp1_svpp2_mdp_color",
	"vpp1_svpp3_mdp_rsz",
	"vpp1_svpp3_vpp_merge",
	"vpp1_svpp3_mdp_tdshp",
	"vpp1_svpp3_mdp_color",
	"vpp1_gals5",
	"vpp1_gals6",
	"vpp1_larb5",
	"vpp1_larb6",
	"vpp1_svpp1_mdp_hdr",
	"vpp1_svpp1_mdp_aal",
	"vpp1_svpp2_mdp_hdr",
	"vpp1_svpp2_mdp_aal",
	"vpp1_svpp3_mdp_hdr",
	"vpp1_svpp3_mdp_aal",
	"vpp1_disp_mutex",
	"vpp1_svpp2_vdo1_dl_relay",
	"vpp1_svpp3_vdo0_dl_relay",
	"vpp1_vpp0_dl_async",
	"vpp1_vpp0_dl1_relay",
	"vpp1_larb5_fake_eng",
	"vpp1_larb6_fake_eng",
	"vpp1_hdmi_meta",
	"vpp1_vpp_split_hdmi",
	"vpp1_dgi_in",
	"vpp1_dgi_out",
	"vpp1_vpp_split_dgi",
	"vpp1_dl_con_occ",
	"vpp1_vpp_split_26m",
	"imgsys_main_larb9",
	"imgsys_main_traw0",
	"imgsys_main_traw1",
	"imgsys_main_vcore_gals",
	"imgsys_main_dip0",
	"imgsys_main_wpe0",
	"imgsys_main_ipe",
	"imgsys_main_wpe1",
	"imgsys_main_wpe2",
	"imgsys_main_gals",
	"imgsys1_dip_larb10",
	"imgsys1_dip_dip_top",
	"imgsys1_dip_nr_larb15",
	"imgsys1_dip_nr_dip_nr",
	"imgsys_wpe1_larb11",
	"imgsys_wpe1",
	"ipe_dpe",
	"ipe_fdvt",
	"ipe_me",
	"ipesys_top",
	"ipe_smi_larb12",
	"imgsys_wpe2_larb11",
	"imgsys_wpe2",
	"imgsys_wpe3_larb11",
	"imgsys_wpe3",
	"cam_main_larb13",
	"cam_main_larb14",
	"cam_main_cam",
	"cam_main_cam_suba",
	"cam_main_cam_subb",
	"cam_main_camtg",
	"cam_main_seninf",
	"cam_main_gcamsva",
	"cam_main_gcamsvb",
	"cam_main_gcamsvc",
	"cam_main_gcamsvd",
	"cam_main_gcamsve",
	"cam_main_gcamsvf",
	"cam_main_gcamsvg",
	"cam_main_gcamsvh",
	"cam_main_gcamsvi",
	"cam_main_gcamsvj",
	"cam_main_camsv_top",
	"cam_main_camsv_cq_a",
	"cam_main_camsv_cq_b",
	"cam_main_camsv_cq_c",
	"cam_main_fake_eng",
	"cam_main_cam2mm0_gals",
	"cam_main_cam2mm1_gals",
	"cam_main_cam2sys_gals",
	"cam_rawa_larbx",
	"cam_rawa_cam",
	"cam_rawa_camtg",
	"cam_yuva_larbx",
	"cam_yuva_cam",
	"cam_yuva_camtg",
	"cam_rawb_larbx",
	"cam_rawb_cam",
	"cam_rawb_camtg",
	"cam_yuvb_larbx",
	"cam_yuvb_cam",
	"cam_yuvb_camtg",
	"ccu_larb27",
	"ccu_ahb",
	"ccu_ccu0",
	"vde1_soc_larb1",
	"vde1_soc_lat",
	"vde1_soc_lat_active",
	"vde1_soc_lat_eng",
	"vde1_soc_vdec",
	"vde1_soc_vdec_active",
	"vde1_soc_vdec_eng",
	"vde2_larb1",
	"vde2_lat",
	"vde2_lat_active",
	"vde2_lat_eng",
	"vde2_vdec",
	"vde2_vdec_active",
	"vde2_vdec_eng",
	"ven1_cke0_larb",
	"ven1_cke1_venc",
	"ven1_cke2_jpgenc",
	"ven1_cke3_jpgdec",
	"ven1_cke4_jpgdec_c1",
	"ven1_cke5_gals",
	"ven1_cke6_gals_sram",
	"vdo0_disp_ovl0",
	"vdo0_fake_eng0",
	"vdo0_disp_ccorr0",
	"vdo0_disp_mutex0",
	"vdo0_disp_gamma0",
	"vdo0_disp_dither0",
	"vdo0_disp_wdma0",
	"vdo0_disp_rdma0",
	"vdo0_dsi0",
	"vdo0_dsi1",
	"vdo0_dsc_wrap0",
	"vdo0_vpp_merge0",
	"vdo0_dp_intf0",
	"vdo0_disp_aal0",
	"vdo0_inlinerot0",
	"vdo0_apb_bus",
	"vdo0_disp_color0",
	"vdo0_mdp_wrot0",
	"vdo0_disp_rsz0",
	"vdo0_disp_postmask0",
	"vdo0_fake_eng1",
	"vdo0_dl_async2",
	"vdo0_dl_relay3",
	"vdo0_dl_relay4",
	"vdo0_smi_gals",
	"vdo0_smi_common",
	"vdo0_smi_emi",
	"vdo0_smi_iommu",
	"vdo0_smi_larb",
	"vdo0_smi_rsi",
	"vdo0_dsi0_dsi",
	"vdo0_dsi1_dsi",
	"vdo0_dp_intf0_dp_intf",
	"vdo1_smi_larb2",
	"vdo1_smi_larb3",
	"vdo1_gals",
	"vdo1_fake_eng0",
	"vdo1_fake_eng1",
	"vdo1_mdp_rdma0",
	"vdo1_mdp_rdma1",
	"vdo1_mdp_rdma2",
	"vdo1_mdp_rdma3",
	"vdo1_vpp_merge0",
	"vdo1_vpp_merge1",
	"vdo1_vpp_merge2",
	"vdo1_vpp_merge3",
	"vdo1_vpp_merge4",
	"vdo1_vpp2_to_vdo1_dl_async",
	"vdo1_vpp3_to_vdo1_dl_async",
	"vdo1_disp_mute",
	"vdo1_mdp_rdma4",
	"vdo1_mdp_rdma5",
	"vdo1_mdp_rdma6",
	"vdo1_mdp_rdma7",
	"vdo1_dp_intf0_mmck",
	"vdo1_dpi0_mm_ck",
	"vdo1_dpi1_mm_ck",
	"vdo1_merge0_dl_async",
	"vdo1_merge1_dl_async",
	"vdo1_merge2_dl_async",
	"vdo1_merge3_dl_async",
	"vdo1_merge4_dl_async",
	"vdo1_dsc_vdo1_dl_async",
	"vdo1_merge_vdo1_dl_async",
	"vdo1_padding0",
	"vdo1_padding1",
	"vdo1_padding2",
	"vdo1_padding3",
	"vdo1_padding4",
	"vdo1_padding5",
	"vdo1_padding6",
	"vdo1_padding7",
	"vdo1_disp_rsz0",
	"vdo1_disp_rsz1",
	"vdo1_disp_rsz2",
	"vdo1_disp_rsz3",
	"vdo1_hdr_vdo_fe0",
	"vdo1_hdr_gfx_fe0",
	"vdo1_hdr_vdo_be",
	"vdo1_hdr_vdo_fe1",
	"vdo1_hdr_gfx_fe1",
	"vdo1_disp_mixer",
	"vdo1_hdr_vdo_fe0_dl_async",
	"vdo1_hdr_vdo_fe1_dl_async",
	"vdo1_hdr_gfx_fe0_dl_async",
	"vdo1_hdr_gfx_fe1_dl_async",
	"vdo1_hdr_vdo_be_dl_async",
	"vdo1_dpi0_ck",
	"vdo1_disp_monitor_dpi0_ck",
	"vdo1_dpi1_ck",
	"vdo1_disp_monitor_dpi1_ck",
	"vdo1_dpintf_ck",
	"vdo1_disp_monitor_dpintf_ck",
	"vdo1_26m_slow_ck",
	NULL,
};

static const char * const *get_all_clk_names(void)
{
	return clk_names;
}

static const char * const *get_pwr_names(void)
{
	static const char * const pwr_names[] = {
		/* PWR_STATUS & PWR_STATUS_2ND */
		[0] = "",
		[1] = "ETHER",
		[2] = "DPY0",
		[3] = "DPY1",
		[4] = "DPM0",
		[5] = "DPM1",
		[6] = "AUDIO",
		[7] = "AUDIO_ASRC",
		[8] = "ADSP",
		[9] = "ADSP_INFRA",
		[10] = "ADSP_AO",
		[11] = "VPPSYS0",
		[12] = "VPPSYS1",
		[13] = "VDOSYS0",
		[14] = "VDOSYS1",
		[15] = "WPESYS",
		[16] = "DP_TX",
		[17] = "EDP_TX",
		[18] = "HDMI_TX",
		[19] = "VDE0",
		[20] = "VDE1",
		[21] = "",
		[22] = "VEN",
		[23] = "",
		[24] = "CAM_MAIN",
		[25] = "CAM_SUBA",
		[26] = "CAM_SUBB",
		[27] = "CAM_VCORE",
		[28] = "IMG_VCORE",
		[29] = "IMG_MAIN",
		[30] = "IMG_DIP",
		[31] = "IMG_IPE",
		/* CPU_PWR_STATUS & CPU_PWR_STATUS_2ND */
		[32] = "MCUPM",
		[33] = "MFG0",
		[34] = "MFG1",
		[35] = "MFG2",
		[36] = "MFG3",
		[37] = "MFG4",
		[38] = "",
		[39] = "IFR",
		[40] = "IFR_SUB",
		[41] = "PERI",
		[42] = "PEXTP_MAC_TOP_P0",
		[43] = "",
		[44] = "PEXTP_PHY_TOP",
		[45] = "",
		[46] = "",
		[47] = "",
		[48] = "",
		[49] = "CSI_RX_TOP",
		[50] = "APHY_N",
		[51] = "APHY_S",
		[52] = "",
		[53] = "",
		[54] = "",
		[55] = "",
		[56] = "",
		[57] = "",
		[58] = "",
		[59] = "",
		[60] = "",
		[61] = "",
		[62] = "",
		[63] = "",
		/* END */
		[64] = NULL,
	};

	return pwr_names;
}

static u32 _get_pwr_status(u32 pwr_sta_ofs, u32 pwr_sta_2nd_ofs)
{
	static void __iomem *pwr_sta, *pwr_sta_2nd;

	pwr_sta = scpsys_base + pwr_sta_ofs;
	pwr_sta_2nd = scpsys_base + pwr_sta_2nd_ofs;

	return readl(pwr_sta) & readl(pwr_sta_2nd);
}

static u32 *get_all_pwr_status(void)
{
	static struct regs {
		u32 pwr_sta_ofs;
		u32 pwr_sta_2nd_ofs;
	} g[] = {
		{0x16c, 0x170},
		{0x174, 0x178},
	};

	static u32 pwr_sta[PWR_STA_GROUP_NR];
	int i;

	for (i = 0; i < PWR_STA_GROUP_NR; i++)
		pwr_sta[i] = _get_pwr_status(g[i].pwr_sta_ofs, g[i].pwr_sta_2nd_ofs);

	return pwr_sta;
}

static struct device_node *get_power_controller(void)
{
	return of_find_compatible_node(NULL, NULL, "mediatek,mt8188-power-controller");
}

/*
 * init functions
 */

static struct clkdbg_ops clkdbg_mt8188_ops = {
	.get_all_fmeter_clks = get_all_fmeter_clks,
	.fmeter_freq = fmeter_freq_op,
	.get_all_clk_names = get_all_clk_names,
	.get_pwr_names = get_pwr_names,
	.get_all_pwr_status = get_all_pwr_status,
	.get_power_controller = get_power_controller,
};

static int clk_dbg_mt8188_probe(struct platform_device *pdev)
{
	pr_notice("%s start\n", __func__);
	set_clkdbg_ops(&clkdbg_mt8188_ops);

	return 0;
}

static struct platform_driver clk_dbg_mt8188_drv = {
	.probe = clk_dbg_mt8188_probe,
	.driver = {
		.name = "clk-dbg-mt8188",
		.owner = THIS_MODULE,
	},
};

/*
 * init functions
 */

static int __init clkdbg_mt8188_init(void)
{
	scpsys_base = ioremap(0x10006000, PAGE_SIZE);
	topck_base = ioremap(0x10000000, PAGE_SIZE);

	return clk_dbg_driver_register(&clk_dbg_mt8188_drv, "clk-dbg-mt8188");
}

static void __exit clkdbg_mt8188_exit(void)
{
	platform_driver_unregister(&clk_dbg_mt8188_drv);
}

subsys_initcall(clkdbg_mt8188_init);
module_exit(clkdbg_mt8188_exit);
MODULE_LICENSE("GPL");
