/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2020 MediaTek Inc.
 */

#ifndef __MT_IOMMU_PLAT_H__
#define __MT_IOMMU_PLAT_H__

/* m4u atf debug parameter */
#define IOMMU_ATF_INDEX_MASK     F_MSK(3, 0)
#define IOMMU_ATF_BANK_MASK      F_MSK(7, 4)
#define IOMMU_ATF_CMD_MASK       F_MSK(16, 8)
#define IOMMU_ATF_SET_COMMAND(m4u, bank, cmd) \
	(m4u | (bank << 4) | (cmd << 8))

enum IOMMU_ATF_CMD {
	IOMMU_ATF_DUMP_SECURE_REG,
	IOMMU_ATF_SECURITY_DEBUG_ENABLE,
	IOMMU_ATF_SECURITY_DEBUG_DISABLE,
	IOMMU_ATF_BANK_ENABLE_TF,
	IOMMU_ATF_BANK_DISABLE_TF,
	IOMMU_ATF_BANK_DUMP_INFO,
	IOMMU_ATF_BANK_DOMAIN_CONFIG,
	IOMMU_ATF_SECURITY_BACKUP,
	IOMMU_ATF_SECURITY_RESTORE,
	IOMMU_ATF_DUMP_SECURE_PORT_CONFIG,
	IOMMU_ATF_SET_SMI_SEC_LARB,
	IOMMU_ATF_DUMP_SMI_SEC_LARB,
	IOMMU_ATF_CMD_COUNT
};

#endif
